
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 42
#define YY_END_OF_BUFFER 43
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[299] =
    {   0,
        0,    0,   43,   41,    1,    1,   41,   41,   41,   38,
       39,   41,   37,   41,   29,   36,   34,   35,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   41,    1,   31,    0,
       22,    0,    0,   29,    2,   26,    0,   29,   25,   27,
        0,    0,   33,   30,   32,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,    8,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,    5,   40,   40,
       40,   40,   40,   13,   11,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,    0,    0,    2,   29,

        0,    0,    0,    0,   40,   40,   40,   40,   10,   40,
       40,   40,   40,   40,   40,   40,   40,   40,    9,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   12,
       13,   40,   40,   15,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,    0,    0,    0,    0,   28,   25,
       40,   40,   40,   40,   15,   40,   15,   40,   40,   40,
       40,    7,   40,   40,   40,   40,   40,   40,   14,   20,
       40,   20,   20,   40,   40,   40,   15,   40,   40,    6,
       13,   14,   40,    3,   40,    0,    0,    0,    0,   23,
       40,   40,   40,   40,   40,   40,   14,   40,   20,   20,

       40,    4,   13,   20,   40,   40,   40,   19,   40,   40,
       40,   15,    0,   21,    0,   40,   18,   19,   40,   15,
       20,   40,   40,   20,   40,   40,   40,   40,   40,   40,
       40,   22,   21,    0,   40,   40,   40,   40,   20,   40,
       40,   40,   40,   40,   20,   21,    0,   20,   40,   40,
       40,   20,   40,   40,   40,   40,   20,   20,    0,   40,
       40,   40,   40,   40,   40,   40,   40,   24,   40,   40,
       16,   40,   40,   40,   40,   20,   40,   17,   40,   16,
       20,   40,   40,   40,   40,   40,   40,   40,   40,   20,
       16,   40,   40,   40,   16,   40,   17,    0

    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    7,    1,    1,    8,
        9,    1,   10,    1,   11,   12,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   15,    1,   16,
       17,   18,    1,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   26,   30,   31,   32,   33,   34,
       26,   35,   36,   37,   38,   39,   40,   41,   42,   43,
        1,    1,    1,    1,   44,    1,   45,   46,   47,   48,

       49,   50,   26,   51,   52,   53,   26,   54,   55,   56,
       57,   58,   26,   59,   60,   61,   62,   63,   64,   41,
       65,   66,    1,    1,    1,    1,    1,   67,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   68,   69,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   70,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   71,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   72,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[73] =
    {   0,
        1,    1,    2,    3,    1,    1,    4,    1,    1,    4,
        5,    5,    1,    5,    1,    1,    1,    1,    4,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    4,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    1,    1,    1,    1,
        1,    1
    } ;

static const flex_int16_t yy_base[310] =
    {   0,
        0,    0,  281, 2158,   71,   74,  258,  265,  250, 2158,
     2158,   65,  246,  249,   78,  244,  243,  238,  143,   76,
      103,   84,  203,  260,  109,  135,  151,  170,  181,  218,
      266,  279,  294,  314,  315,  237,  187,   78, 2158,  246,
     2158,  232,    0,  234,    0,  227,   79,  170,  226,  222,
       82,  170, 2158, 2158, 2158,  127,  325,  335,  348,  359,
      377,  385,  391,  401,  414,  415,  162,  425,  444,  455,
      465,  469,  480,  369,  494,  502,  488,  510,  521,  525,
      539,  545,  549,  553,  559,  573,  574,  595,  584,  609,
      605,  623,  619,  643,  644,  654,  168,  219,    0,   75,

      215,  207,   83,   96,  673,  681,  677,  697,  701,  714,
      722,  728,  736,  746,  750,  763,  764,  774,  782,  788,
      804,  805,  815,  825,  836,  840,  860,  861,  876,  880,
      891,  895,  905,  909,  920,  928,  939,  952,  960,  971,
      977,  981,  994, 1005,  144,  145,  198,  197,  187, 2158,
     1015, 1011, 1021, 1025, 1029, 1039, 1050, 1060, 1061, 1082,
     1088, 1096, 1106, 1114, 1122, 1132, 1133, 1147, 1151, 1161,
     1165, 1176, 1182, 1186, 1190, 1196, 1209, 1210, 1220, 1234,
     1235, 1249, 1250, 1263, 1264,  130,   32,  193,  185, 2158,
     1277, 1283, 1291, 1297, 1305, 1313, 1321, 1332, 1338, 1346,

     1354, 1362, 1372, 1376, 1386, 1382, 1397, 1407, 1411, 1421,
     1438, 1425,   95,  206,  182, 1446, 1461, 1465, 1469, 1479,
     1483, 1489, 1504, 1503, 1514, 1518, 1522, 1533, 1537, 1554,
     1571,  115,  212,  165, 1575, 1579, 1589, 1595, 1599, 1619,
     1603, 1658, 1630, 1634, 1650,  166,  152, 1664, 1686, 1692,
     1708, 1714, 1718, 1728, 1729, 1739, 1757, 1758,  137, 1777,
     1787, 1791, 1801, 1816, 1817, 1830, 1844, 2158, 1852, 1866,
     1876, 1882, 1897, 1907, 1901, 1920, 1926, 1940, 1944, 1950,
     1958, 1966, 1972, 1976, 1990, 1991, 2004, 2025, 2024, 2043,
     2047, 2051, 2057, 2065, 2078, 2079, 2089, 2158, 2136, 2138,

     2140,  135, 2145, 2150,  126,  121, 2152,  107,  102
    } ;

static const flex_int16_t yy_def[310] =
    {   0,
      298,    1,  298,  298,  298,  298,  298,  299,  300,  298,
      298,  300,  300,  298,  300,  298,  298,  298,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  298,  298,  298,  299,
      298,  300,  302,   15,  303,  300,  300,   15,  300,  300,
      300,  298,  298,  298,  298,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  298,  302,  303,   15,

      298,  298,  300,  298,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  304,  305,  298,  298,  300,  298,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  304,  304,  306,  298,  298,
      301,  307,  301,  301,  301,  301,  301,  301,  301,  301,

      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  304,  308,  298,  301,  307,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  304,  309,  298,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  302,  298,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  298,  301,
      301,  301,  301,  301,  301,  301,  301,  298,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,    0,  298,  298,

      298,  298,  298,  298,  298,  298,  298,  298,  298
    } ;

static const flex_int16_t yy_nxt[2231] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,    9,
       12,   13,   14,   15,    4,   16,   17,   18,    4,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   25,   25,
       28,   29,   30,   31,   32,   33,   34,   25,   35,   36,
       25,   25,   25,   25,   19,   20,   21,   22,   23,   24,
       26,   27,   25,   25,   28,   29,   30,   31,   32,   33,
       34,   25,   35,   36,   25,   25,    4,    4,    4,    4,
        4,   37,   38,   38,   38,   38,   38,   38,   44,   38,
       38,   38,   42,   43,   46,   42,   42,   42,  100,   47,
       42,   48,  100,   42,   43,   42,   43,   43,  213,   49,

       43,   43,   43,  187,   50,   62,  246,   51,   50,   42,
       63,  233,   42,   50,   42,   42,   67,  150,   42,  103,
       42,   43,   64,  149,   49,  214,   65,   43,   50,   62,
      188,   51,   50,   42,   63,   66,   42,   50,   42,   98,
       67,   42,  150,  103,   42,   43,   42,   64,   52,   42,
      268,   65,   42,   43,   42,   98,  146,   42,   98,   66,
       42,   43,   42,  232,   57,  259,  187,   77,   42,   43,
       58,   42,   59,   42,   60,   78,   42,  146,  247,   42,
       43,   42,  101,   44,  102,   61,  187,   42,   43,   57,
       42,   77,   42,   79,   58,  234,   59,  215,   60,   43,

       78,  187,   80,   98,  146,   43,   98,   81,   61,   42,
      190,  189,   42,   82,   42,  187,   98,  146,   79,   98,
      148,   43,   98,  146,   42,   98,   80,   42,  147,   42,
      146,   81,   68,   69,   70,  145,   43,   82,   71,  104,
       43,   72,   83,   42,   43,   43,   42,   44,   42,   84,
       43,   41,   85,   97,   55,   43,   68,   69,   70,   54,
       53,   45,   71,   96,   43,   72,   42,   83,   43,   42,
       41,   42,   42,   84,   39,   42,   85,   42,   43,   73,
      298,  298,  298,   74,   43,   42,  298,   96,   42,   86,
       42,  298,   75,  298,   76,  298,  298,   43,   87,  298,

       42,  298,   88,   42,   73,   42,  298,  298,   74,  298,
      298,   89,   43,  298,   86,  298,   75,   90,   76,  298,
       42,   42,   87,   42,   42,   42,   42,   88,  298,  298,
      298,   42,   43,   43,   42,   89,   42,   91,   94,  298,
       92,   42,   90,   43,   42,  298,   42,   95,   93,  298,
      298,  298,  298,   43,   42,  298,  298,   42,  298,   42,
      298,  105,   91,   94,   92,   42,   43,  107,   42,  106,
       42,   95,   93,  298,  298,   42,  298,   43,   42,  298,
       42,  109,  298,   42,  108,  105,   42,   43,   42,  298,
      123,   42,  107,  106,   42,   43,   42,   42,  298,  298,

       42,  298,   42,   43,  111,  298,  109,   42,  108,   43,
       42,  298,   42,  298,  110,  123,  298,  298,  113,   43,
       42,   42,  112,   42,   42,   42,   42,  298,  298,  111,
      114,   42,   43,   43,   42,  298,   42,  298,  110,  298,
      298,  298,  113,   43,  116,  298,  112,  298,  115,  298,
       42,  298,  298,   42,  114,   42,  298,  298,  298,  298,
      117,   42,   43,  118,   42,  298,   42,  298,  116,  298,
      298,   42,  115,   43,   42,   42,   42,  119,   42,  298,
       42,  298,  298,   43,  117,  298,   42,   43,  118,   42,
      298,   42,  121,  298,   42,  298,  298,   42,   43,   42,

       42,  120,  119,   42,  298,   42,   43,  298,   42,  122,
      298,   42,   43,   42,  298,  124,   42,  121,  298,   42,
       43,   42,  126,  298,  298,  120,  298,   42,   43,  125,
       42,   42,   42,  122,   42,  298,   42,  298,  298,   43,
      124,  298,  298,   43,  298,   42,  126,  128,   42,  298,
       42,   42,  127,  125,   42,   42,   42,   43,   42,   42,
       42,  298,   42,   43,   42,   42,  298,   43,   42,  298,
       42,   43,  128,  131,  298,  129,  127,   43,  298,   42,
       42,  130,   42,   42,   42,   42,  298,  298,  298,  298,
       42,   43,   43,   42,  298,   42,  298,  298,  131,  129,

      298,   42,   43,  298,   42,  130,   42,  132,  298,  133,
      298,   42,  136,   43,   42,   42,   42,  134,   42,  298,
       42,  298,  298,   43,  135,   42,  298,   43,   42,   42,
       42,  132,   42,  133,   42,  138,  136,   43,  298,  298,
      137,   43,  134,  298,  298,  298,  139,  298,  135,   42,
       42,  298,   42,   42,   42,   42,  140,  298,  298,  138,
       42,   43,   43,   42,  137,   42,  298,  298,  298,  298,
      298,  139,   43,  142,  141,  298,  298,  143,  298,   42,
      140,  144,   42,   42,   42,  298,   42,   42,   42,  298,
       42,   43,   42,  298,  298,   43,  298,  142,  141,   43,

      151,  298,  143,   42,  152,  144,   42,   42,   42,  298,
       42,  153,   42,  298,  298,   43,  154,  298,  298,   43,
       42,  298,  298,   42,  151,   42,  298,  298,   42,  152,
      298,   42,   43,   42,   42,  153,  298,   42,  298,   42,
       43,  154,   42,  155,  298,   42,   43,   42,  298,  298,
      298,  157,   42,  156,   43,   42,   42,   42,  298,   42,
      298,   42,  298,  298,   43,  158,  298,  155,   43,   42,
       42,  298,   42,   42,   42,   42,  157,  156,  159,  298,
       42,   43,   43,   42,  160,   42,  298,  162,   42,  158,
      298,   42,   43,   42,   42,  161,  298,   42,  298,   42,

       43,  163,  159,  298,  298,  298,   43,  164,  160,  298,
       42,   42,  162,   42,   42,   42,   42,  298,  298,  161,
      298,   42,   43,   43,   42,  163,   42,  298,  298,  298,
      298,   42,  164,   43,   42,  298,   42,  298,  165,  298,
      166,  167,   42,   43,  298,   42,   42,   42,  298,   42,
      298,   42,  298,  298,   43,  298,  298,  168,   43,  170,
      298,  298,  165,  298,  166,  167,   42,   42,  169,   42,
       42,   42,   42,  298,  298,  298,  298,  298,   43,   43,
      298,  168,   42,  298,  170,   42,   42,   42,  298,   42,
      298,   42,  169,  172,   43,  171,  298,   42,   43,  173,

       42,   42,   42,  298,   42,  298,   42,  298,  298,   43,
      298,   42,  298,   43,   42,   42,   42,  172,   42,  171,
       42,  298,  298,   43,  173,  298,   42,   43,  298,   42,
      174,   42,  175,  298,   42,  298,  298,   42,   43,   42,
      298,  298,  298,  298,  298,   42,   43,  298,   42,  298,
       42,  298,  176,  298,  174,  298,  175,   43,   42,  298,
      177,   42,  298,   42,  298,  298,   42,  298,  298,   42,
       43,   42,  298,  298,  178,  298,  176,   42,   43,  298,
       42,  298,   42,   42,  177,  179,   42,   42,   42,   43,
       42,  180,   42,  298,  181,   43,  298,  298,  178,   43,

       42,  298,  298,   42,  298,   42,  298,  298,  298,  179,
      298,   42,   43,  182,   42,  180,   42,   42,  183,  181,
       42,   42,   42,   43,   42,  184,   42,   42,  298,   43,
       42,   42,   42,   43,   42,   42,   42,  182,   42,   43,
       42,  185,  183,   43,  298,   42,  298,   43,   42,  184,
       42,  193,  298,  191,  192,  298,   42,   43,  298,   42,
      195,   42,  298,  194,  298,  185,   42,   42,   43,   42,
       42,   42,   42,  298,  298,  193,  298,  191,   43,   43,
      298,  298,  298,  298,  298,  195,  298,  194,   42,  196,
      298,   42,  298,   42,   42,  197,  298,   42,  298,   42,

       43,  198,   42,  298,  298,   42,   43,   42,  298,  298,
      298,  298,   42,  196,   43,   42,  298,   42,  298,  197,
       42,  298,  199,   42,   43,   42,  198,  298,   42,  298,
      298,   42,   43,   42,  298,  200,  201,  298,   42,   42,
       43,   42,   42,   42,   42,  298,  199,  298,  298,  298,
       43,   43,  204,   42,  298,  203,   42,   42,   42,  200,
       42,  201,   42,  202,  298,   43,  298,   42,  298,   43,
       42,   42,   42,  298,   42,  298,   42,  204,  298,   43,
      203,  298,   42,   43,  205,   42,  202,   42,   42,  298,
      192,   42,   42,   42,   43,   42,   42,   42,  298,   42,

       43,   42,   42,  298,   43,   42,  298,   42,   43,  205,
      298,  207,  298,  206,   43,   42,   42,  298,   42,   42,
       42,   42,  298,  298,  208,  298,   42,   43,   43,   42,
      298,   42,  298,  298,  298,  298,  207,  206,   43,  298,
       42,   42,  209,   42,   42,   42,   42,  298,  208,  298,
      298,  298,   43,   43,  298,   42,   42,  298,   42,   42,
       42,   42,  298,  210,  298,  298,  209,   43,   43,   42,
       42,  298,   42,   42,   42,   42,  298,  298,  298,  298,
      211,   43,   43,   42,  298,  298,   42,  212,   42,   42,
      298,  298,   42,  298,   42,   43,  216,   42,  298,  298,

       42,   43,   42,   42,  211,  298,   42,  298,   42,   43,
      218,   42,  212,  298,   42,   43,   42,  298,  298,   42,
      298,  216,   42,   43,   42,  298,  298,   42,  298,  219,
       42,   43,   42,  298,  298,  218,  298,  220,   42,   43,
      298,   42,  298,   42,   42,  221,  298,   42,  298,   42,
       43,  298,   42,  219,  222,   42,   43,   42,  298,  298,
       42,  220,  298,   42,   43,   42,  298,  298,   42,  221,
      298,   42,   43,   42,  298,  298,  298,  298,   42,  222,
       43,   42,   42,   42,  298,   42,  224,   42,   42,  223,
       43,   42,   42,   42,   43,   42,  298,   42,  298,  298,

       43,  226,  298,   42,   43,  298,   42,  298,   42,  298,
      224,  298,  298,   42,  225,   43,   42,   42,   42,  298,
       42,  298,   42,  298,  227,   43,  226,   42,  298,   43,
       42,   42,   42,  298,   42,  298,   42,  298,  225,   43,
      229,  298,  298,   43,   42,  228,  298,   42,  227,   42,
      192,  298,   42,  230,  298,   42,   43,   42,  298,  298,
      298,  231,  298,  298,   43,  229,  298,   42,  235,  228,
       42,   42,   42,  298,   42,   42,   42,  230,   42,   43,
       42,  298,  298,   43,  298,   42,  231,   43,   42,   42,
       42,  298,   42,  235,   42,   42,  298,   43,   42,  298,

       42,   43,  298,  298,  298,  298,  298,   43,  192,   42,
       42,  236,   42,   42,   42,   42,  298,  298,  298,  298,
       42,   43,   43,   42,   42,   42,  237,   42,   42,   42,
      298,   42,   43,   42,  236,  238,   43,  239,  298,   42,
       43,  298,   42,   42,   42,  298,   42,  298,   42,  240,
      237,   43,  298,  298,  241,   43,  298,  298,  243,  238,
       42,  298,  239,   42,  298,   42,  298,  298,  298,  298,
      298,  298,   43,  240,  244,  298,  242,   42,  241,  298,
       42,   42,   42,  243,   42,   42,   42,  298,   42,   43,
       42,  298,  298,   43,  248,   42,  298,   43,   42,  244,

       42,   42,  245,  298,   42,   42,   42,   43,   42,   42,
       42,  298,   42,   43,   42,  298,  298,   43,  298,  248,
      298,   43,  192,  249,  298,   42,  245,  250,   42,  298,
       42,  298,  298,  298,  252,  298,   42,   43,  251,   42,
       42,   42,  298,   42,  298,   42,  298,  249,   43,  298,
      298,  250,   43,  298,  298,  298,   42,  298,  252,   42,
      298,   42,  258,  251,   42,  298,  257,   42,   43,   42,
       42,  298,  298,   42,  298,   42,   43,  298,  298,  298,
      298,  298,   43,  298,  253,  298,  258,  254,  255,  298,
      257,  298,   42,  298,  256,   42,  298,   42,   42,  298,

      298,   42,  298,   42,   43,  260,  298,  298,  253,  298,
       43,  254,  255,  298,   42,  298,  298,   42,  256,   42,
       42,  298,  298,   42,   42,   42,   43,   42,  261,   42,
      260,  298,   43,  298,   42,   42,   43,   42,   42,   42,
       42,  298,  298,  298,  298,   42,   43,   43,   42,  298,
       42,  192,  261,  298,  298,  262,  298,   43,  298,  298,
      298,  264,  265,   42,   42,  263,   42,   42,   42,   42,
      298,  298,  298,  298,  298,   43,   43,  298,  298,  262,
      298,  267,  298,   42,  298,  264,   42,  265,   42,  263,
      298,  298,  298,   42,  266,   43,   42,   42,   42,  298,

       42,  298,   42,  298,  298,   43,  267,   42,  298,   43,
       42,  298,   42,  298,  269,  298,  298,  298,  266,   43,
      192,  270,   42,   42,  298,   42,   42,   42,   42,  298,
      298,  298,  298,  298,   43,   43,   42,  298,  269,   42,
      298,   42,  298,  271,  298,  270,  298,  273,   43,  274,
       42,  298,  298,   42,  272,   42,  298,  298,   42,  298,
      298,   42,   43,   42,  298,  298,  271,  298,  298,  298,
       43,  273,   42,  298,  274,   42,  276,   42,  272,  298,
      275,  298,   42,  298,   43,   42,  298,   42,   42,  277,
      298,   42,  298,   42,   43,  298,  298,  298,  278,  298,

       43,  276,  298,   42,  275,  298,   42,   42,   42,  279,
       42,  298,   42,   42,  277,   43,   42,  298,   42,   43,
      298,  298,  278,  298,  298,   43,   42,  298,  282,   42,
      280,   42,   42,  279,  298,   42,  281,   42,   43,  298,
      298,  298,  298,  298,   43,  298,   42,  298,  283,   42,
       42,   42,  282,   42,  280,   42,   42,  298,   43,   42,
      281,   42,   43,  298,   42,  298,  298,   42,   43,   42,
      298,  298,   42,  283,  284,   42,   43,   42,   42,  298,
      298,   42,   42,   42,   43,   42,  298,   42,  298,  298,
       43,  287,  298,  285,   43,  298,   42,   42,  284,   42,

       42,   42,   42,  288,  286,  298,  298,  298,   43,   43,
       42,  298,  298,   42,  298,   42,  287,  289,  298,  298,
      298,  298,   43,  290,  298,  298,  291,  288,  286,  298,
       42,   42,  298,   42,   42,   42,   42,  298,  298,  298,
      298,  289,   43,   43,  298,  298,  298,  290,  292,   42,
      298,  291,   42,   42,   42,  293,   42,   42,   42,  298,
       42,   43,   42,   42,  298,   43,   42,  298,   42,   43,
      298,   42,  298,  292,   42,   43,   42,  298,  298,  293,
      298,  298,  294,   43,   42,   42,  298,   42,   42,   42,
       42,  298,  298,  295,  298,   42,   43,   43,   42,  298,

       42,  296,  298,  298,  298,  298,  294,   43,  298,  298,
      298,  297,  298,  298,  298,  298,  298,  295,  298,  298,
      298,  298,  298,  298,  298,  296,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  297,   40,  298,  298,   40,
       40,   42,   42,   56,   56,   99,  298,   99,   99,   99,
      186,  298,  298,  186,  186,  217,  217,    3,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,

      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298
    } ;

static const flex_int16_t yy_chk[2231] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    5,    5,    5,    6,    6,    6,   12,   38,
       38,   38,   20,   12,   15,   20,  100,   20,  100,   15,
       22,   15,   47,   22,   20,   22,   15,   47,  187,   15,

       51,  103,   22,  187,   15,   20,  309,   15,   15,   21,
       20,  308,   21,   15,   21,   25,   22,  104,   25,   51,
       25,   21,   21,  103,   15,  306,   21,   25,   15,   20,
      305,   15,   15,   56,   20,   21,   56,   15,   56,  302,
       22,   26,  104,   51,   26,   56,   26,   21,   15,   19,
      259,   21,   19,   26,   19,  146,  146,   27,  146,   21,
       27,   19,   27,  213,   19,  247,  213,   26,   67,   27,
       19,   67,   19,   67,   19,   27,   28,  246,  234,   28,
       67,   28,   48,   48,   48,   19,  232,   29,   28,   19,
       29,   26,   29,   28,   19,  215,   19,  189,   19,   29,

       27,  186,   28,  188,  188,  149,  188,   28,   19,   23,
      148,  147,   23,   29,   23,  145,  214,  214,   28,  214,
      102,   23,  233,  233,   30,  233,   28,   30,  101,   30,
       98,   28,   23,   23,   23,   97,   30,   29,   23,   52,
       50,   23,   30,   36,   49,   46,   36,   44,   36,   30,
       42,   40,   30,   37,   18,   36,   23,   23,   23,   17,
       16,   14,   23,   36,   13,   23,   24,   30,    9,   24,
        8,   24,   31,   30,    7,   31,   30,   31,   24,   24,
        3,    0,    0,   24,   31,   32,    0,   36,   32,   31,
       32,    0,   24,    0,   24,    0,    0,   32,   31,    0,

       33,    0,   32,   33,   24,   33,    0,    0,   24,    0,
        0,   32,   33,    0,   31,    0,   24,   33,   24,    0,
       34,   35,   31,   34,   35,   34,   35,   32,    0,    0,
        0,   57,   34,   35,   57,   32,   57,   34,   35,    0,
       34,   58,   33,   57,   58,    0,   58,   35,   34,    0,
        0,    0,    0,   58,   59,    0,    0,   59,    0,   59,
        0,   57,   34,   35,   34,   60,   59,   59,   60,   58,
       60,   35,   34,    0,    0,   74,    0,   60,   74,    0,
       74,   60,    0,   61,   59,   57,   61,   74,   61,    0,
       74,   62,   59,   58,   62,   61,   62,   63,    0,    0,

       63,    0,   63,   62,   62,    0,   60,   64,   59,   63,
       64,    0,   64,    0,   61,   74,    0,    0,   63,   64,
       65,   66,   62,   65,   66,   65,   66,    0,    0,   62,
       64,   68,   65,   66,   68,    0,   68,    0,   61,    0,
        0,    0,   63,   68,   66,    0,   62,    0,   65,    0,
       69,    0,    0,   69,   64,   69,    0,    0,    0,    0,
       68,   70,   69,   69,   70,    0,   70,    0,   66,    0,
        0,   71,   65,   70,   71,   72,   71,   70,   72,    0,
       72,    0,    0,   71,   68,    0,   73,   72,   69,   73,
        0,   73,   72,    0,   77,    0,    0,   77,   73,   77,

       75,   71,   70,   75,    0,   75,   77,    0,   76,   73,
        0,   76,   75,   76,    0,   75,   78,   72,    0,   78,
       76,   78,   77,    0,    0,   71,    0,   79,   78,   76,
       79,   80,   79,   73,   80,    0,   80,    0,    0,   79,
       75,    0,    0,   80,    0,   81,   77,   80,   81,    0,
       81,   82,   79,   76,   82,   83,   82,   81,   83,   84,
       83,    0,   84,   82,   84,   85,    0,   83,   85,    0,
       85,   84,   80,   83,    0,   81,   79,   85,    0,   86,
       87,   82,   86,   87,   86,   87,    0,    0,    0,    0,
       89,   86,   87,   89,    0,   89,    0,    0,   83,   81,

        0,   88,   89,    0,   88,   82,   88,   86,    0,   87,
        0,   91,   89,   88,   91,   90,   91,   88,   90,    0,
       90,    0,    0,   91,   88,   93,    0,   90,   93,   92,
       93,   86,   92,   87,   92,   91,   89,   93,    0,    0,
       90,   92,   88,    0,    0,    0,   92,    0,   88,   94,
       95,    0,   94,   95,   94,   95,   93,    0,    0,   91,
       96,   94,   95,   96,   90,   96,    0,    0,    0,    0,
        0,   92,   96,   95,   94,    0,    0,   96,    0,  105,
       93,   96,  105,  107,  105,    0,  107,  106,  107,    0,
      106,  105,  106,    0,    0,  107,    0,   95,   94,  106,

      105,    0,   96,  108,  106,   96,  108,  109,  108,    0,
      109,  107,  109,    0,    0,  108,  108,    0,    0,  109,
      110,    0,    0,  110,  105,  110,    0,    0,  111,  106,
        0,  111,  110,  111,  112,  107,    0,  112,    0,  112,
      111,  108,  113,  110,    0,  113,  112,  113,    0,    0,
        0,  112,  114,  111,  113,  114,  115,  114,    0,  115,
        0,  115,    0,    0,  114,  113,    0,  110,  115,  116,
      117,    0,  116,  117,  116,  117,  112,  111,  114,    0,
      118,  116,  117,  118,  115,  118,    0,  117,  119,  113,
        0,  119,  118,  119,  120,  116,    0,  120,    0,  120,

      119,  118,  114,    0,    0,    0,  120,  120,  115,    0,
      121,  122,  117,  121,  122,  121,  122,    0,    0,  116,
        0,  123,  121,  122,  123,  118,  123,    0,    0,    0,
        0,  124,  120,  123,  124,    0,  124,    0,  121,    0,
      122,  123,  125,  124,    0,  125,  126,  125,    0,  126,
        0,  126,    0,    0,  125,    0,    0,  124,  126,  126,
        0,    0,  121,    0,  122,  123,  127,  128,  125,  127,
      128,  127,  128,    0,    0,    0,    0,    0,  127,  128,
        0,  124,  129,    0,  126,  129,  130,  129,    0,  130,
        0,  130,  125,  128,  129,  127,    0,  131,  130,  129,

      131,  132,  131,    0,  132,    0,  132,    0,    0,  131,
        0,  133,    0,  132,  133,  134,  133,  128,  134,  127,
      134,    0,    0,  133,  129,    0,  135,  134,    0,  135,
      132,  135,  133,    0,  136,    0,    0,  136,  135,  136,
        0,    0,    0,    0,    0,  137,  136,    0,  137,    0,
      137,    0,  135,    0,  132,    0,  133,  137,  138,    0,
      136,  138,    0,  138,    0,    0,  139,    0,    0,  139,
      138,  139,    0,    0,  137,    0,  135,  140,  139,    0,
      140,    0,  140,  141,  136,  138,  141,  142,  141,  140,
      142,  139,  142,    0,  140,  141,    0,    0,  137,  142,

      143,    0,    0,  143,    0,  143,    0,    0,    0,  138,
        0,  144,  143,  141,  144,  139,  144,  152,  142,  140,
      152,  151,  152,  144,  151,  143,  151,  153,    0,  152,
      153,  154,  153,  151,  154,  155,  154,  141,  155,  153,
      155,  144,  142,  154,    0,  156,    0,  155,  156,  143,
      156,  153,    0,  151,  152,    0,  157,  156,    0,  157,
      156,  157,    0,  154,    0,  144,  158,  159,  157,  158,
      159,  158,  159,    0,    0,  153,    0,  151,  158,  159,
        0,    0,    0,    0,    0,  156,    0,  154,  160,  158,
        0,  160,    0,  160,  161,  159,    0,  161,    0,  161,

      160,  160,  162,    0,    0,  162,  161,  162,    0,    0,
        0,    0,  163,  158,  162,  163,    0,  163,    0,  159,
      164,    0,  161,  164,  163,  164,  160,    0,  165,    0,
        0,  165,  164,  165,    0,  163,  164,    0,  166,  167,
      165,  166,  167,  166,  167,    0,  161,    0,    0,    0,
      166,  167,  167,  168,    0,  166,  168,  169,  168,  163,
      169,  164,  169,  165,    0,  168,    0,  170,    0,  169,
      170,  171,  170,    0,  171,    0,  171,  167,    0,  170,
      166,    0,  172,  171,  171,  172,  165,  172,  173,    0,
      168,  173,  174,  173,  172,  174,  175,  174,    0,  175,

      173,  175,  176,    0,  174,  176,    0,  176,  175,  171,
        0,  175,    0,  174,  176,  177,  178,    0,  177,  178,
      177,  178,    0,    0,  176,    0,  179,  177,  178,  179,
        0,  179,    0,    0,    0,    0,  175,  174,  179,    0,
      180,  181,  178,  180,  181,  180,  181,    0,  176,    0,
        0,    0,  180,  181,    0,  182,  183,    0,  182,  183,
      182,  183,    0,  179,    0,    0,  178,  182,  183,  184,
      185,    0,  184,  185,  184,  185,    0,    0,    0,    0,
      183,  184,  185,  191,    0,    0,  191,  185,  191,  192,
        0,    0,  192,    0,  192,  191,  191,  193,    0,    0,

      193,  192,  193,  194,  183,    0,  194,    0,  194,  193,
      193,  195,  185,    0,  195,  194,  195,    0,    0,  196,
        0,  191,  196,  195,  196,    0,    0,  197,    0,  194,
      197,  196,  197,    0,    0,  193,    0,  195,  198,  197,
        0,  198,    0,  198,  199,  196,    0,  199,    0,  199,
      198,    0,  200,  194,  198,  200,  199,  200,    0,    0,
      201,  195,    0,  201,  200,  201,    0,    0,  202,  196,
        0,  202,  201,  202,    0,    0,    0,    0,  203,  198,
      202,  203,  204,  203,    0,  204,  201,  204,  206,  200,
      203,  206,  205,  206,  204,  205,    0,  205,    0,    0,

      206,  206,    0,  207,  205,    0,  207,    0,  207,    0,
      201,    0,    0,  208,  205,  207,  208,  209,  208,    0,
      209,    0,  209,    0,  207,  208,  206,  210,    0,  209,
      210,  212,  210,    0,  212,    0,  212,    0,  205,  210,
      210,    0,    0,  212,  211,  209,    0,  211,  207,  211,
      208,    0,  216,  210,    0,  216,  211,  216,    0,    0,
        0,  211,    0,    0,  216,  210,    0,  217,  216,  209,
      217,  218,  217,    0,  218,  219,  218,  210,  219,  217,
      219,    0,    0,  218,    0,  220,  211,  219,  220,  221,
      220,    0,  221,  216,  221,  222,    0,  220,  222,    0,

      222,  221,    0,    0,    0,    0,    0,  222,  218,  224,
      223,  219,  224,  223,  224,  223,    0,    0,    0,    0,
      225,  224,  223,  225,  226,  225,  222,  226,  227,  226,
        0,  227,  225,  227,  219,  223,  226,  225,    0,  228,
      227,    0,  228,  229,  228,    0,  229,    0,  229,  226,
      222,  228,    0,    0,  227,  229,    0,    0,  229,  223,
      230,    0,  225,  230,    0,  230,    0,    0,    0,    0,
        0,    0,  230,  226,  230,    0,  228,  231,  227,    0,
      231,  235,  231,  229,  235,  236,  235,    0,  236,  231,
      236,    0,    0,  235,  235,  237,    0,  236,  237,  230,

      237,  238,  231,    0,  238,  239,  238,  237,  239,  241,
      239,    0,  241,  238,  241,    0,    0,  239,    0,  235,
        0,  241,  236,  237,    0,  240,  231,  238,  240,    0,
      240,    0,    0,    0,  241,    0,  243,  240,  240,  243,
      244,  243,    0,  244,    0,  244,    0,  237,  243,    0,
        0,  238,  244,    0,    0,    0,  245,    0,  241,  245,
        0,  245,  244,  240,  242,    0,  243,  242,  245,  242,
      248,    0,    0,  248,    0,  248,  242,    0,    0,    0,
        0,    0,  248,    0,  242,    0,  244,  242,  242,    0,
      243,    0,  249,    0,  242,  249,    0,  249,  250,    0,

        0,  250,    0,  250,  249,  249,    0,    0,  242,    0,
      250,  242,  242,    0,  251,    0,    0,  251,  242,  251,
      252,    0,    0,  252,  253,  252,  251,  253,  250,  253,
      249,    0,  252,    0,  254,  255,  253,  254,  255,  254,
      255,    0,    0,    0,    0,  256,  254,  255,  256,    0,
      256,  251,  250,    0,    0,  253,    0,  256,    0,    0,
        0,  255,  256,  257,  258,  254,  257,  258,  257,  258,
        0,    0,    0,    0,    0,  257,  258,    0,    0,  253,
        0,  258,    0,  260,    0,  255,  260,  256,  260,  254,
        0,    0,    0,  261,  257,  260,  261,  262,  261,    0,

      262,    0,  262,    0,    0,  261,  258,  263,    0,  262,
      263,    0,  263,    0,  261,    0,    0,    0,  257,  263,
      260,  262,  264,  265,    0,  264,  265,  264,  265,    0,
        0,    0,    0,    0,  264,  265,  266,    0,  261,  266,
        0,  266,    0,  263,    0,  262,    0,  265,  266,  266,
      267,    0,    0,  267,  264,  267,    0,    0,  269,    0,
        0,  269,  267,  269,    0,    0,  263,    0,    0,    0,
      269,  265,  270,    0,  266,  270,  269,  270,  264,    0,
      267,    0,  271,    0,  270,  271,    0,  271,  272,  270,
        0,  272,    0,  272,  271,    0,    0,    0,  270,    0,

      272,  269,    0,  273,  267,    0,  273,  275,  273,  272,
      275,    0,  275,  274,  270,  273,  274,    0,  274,  275,
        0,    0,  270,    0,    0,  274,  276,    0,  275,  276,
      273,  276,  277,  272,    0,  277,  274,  277,  276,    0,
        0,    0,    0,    0,  277,    0,  278,    0,  277,  278,
      279,  278,  275,  279,  273,  279,  280,    0,  278,  280,
      274,  280,  279,    0,  281,    0,    0,  281,  280,  281,
        0,    0,  282,  277,  279,  282,  281,  282,  283,    0,
        0,  283,  284,  283,  282,  284,    0,  284,    0,    0,
      283,  283,    0,  280,  284,    0,  285,  286,  279,  285,

      286,  285,  286,  284,  282,    0,    0,    0,  285,  286,
      287,    0,    0,  287,    0,  287,  283,  285,    0,    0,
        0,    0,  287,  286,    0,    0,  287,  284,  282,    0,
      289,  288,    0,  289,  288,  289,  288,    0,    0,    0,
        0,  285,  289,  288,    0,    0,    0,  286,  288,  290,
        0,  287,  290,  291,  290,  289,  291,  292,  291,    0,
      292,  290,  292,  293,    0,  291,  293,    0,  293,  292,
        0,  294,    0,  288,  294,  293,  294,    0,    0,  289,
        0,    0,  292,  294,  295,  296,    0,  295,  296,  295,
      296,    0,    0,  293,    0,  297,  295,  296,  297,    0,

      297,  294,    0,    0,    0,    0,  292,  297,    0,    0,
        0,  296,    0,    0,    0,    0,    0,  293,    0,    0,
        0,    0,    0,    0,    0,  294,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  296,  299,    0,    0,  299,
      299,  300,  300,  301,  301,  303,    0,  303,  303,  303,
      304,    0,    0,  304,  304,  307,  307,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,

      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[43] =
    {   0,
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "smart_home.l"
/* Lexer SMART-HOME simple.
   Reconoce los tokens usados por los ejemplos de ejemplosValidosSmart. */
#define YY_NO_INPUT 1
#line 11 "smart_home.l"
#include <stdio.h>
#include "smart_home.tab.h"

static int errores_lexicos = 0;

static void imprimir_token(const char *tipo, const char *valor) {
    printf("Linea %-3d | %-24s | %s\n", yylineno, tipo, valor);
}

int obtener_errores_lexicos(void) {
    return errores_lexicos;
}

#ifdef LEXER_STANDALONE
#define TOKEN(tipo, nombre) do { imprimir_token((nombre), yytext); return (tipo); } while (0)
#else
#define TOKEN(tipo, nombre) return (tipo)
#endif
#line 1084 "lex.yy.c"
#line 1085 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 44 "smart_home.l"


#line 1303 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 299 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 2158 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 46 "smart_home.l"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 47 "smart_home.l"
;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 49 "smart_home.l"
{ TOKEN(TOKEN_WHEN, "TOKEN_WHEN"); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 50 "smart_home.l"
{ TOKEN(TOKEN_EVERY, "TOKEN_EVERY"); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 51 "smart_home.l"
{ TOKEN(TOKEN_IF, "TOKEN_IF"); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 52 "smart_home.l"
{ TOKEN(TOKEN_THEN, "TOKEN_THEN"); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 53 "smart_home.l"
{ TOKEN(TOKEN_ELSE, "TOKEN_ELSE"); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 54 "smart_home.l"
{ TOKEN(TOKEN_DO, "TOKEN_DO"); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 55 "smart_home.l"
{ TOKEN(TOKEN_END, "TOKEN_END"); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 56 "smart_home.l"
{ TOKEN(TOKEN_AND, "TOKEN_AND"); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 57 "smart_home.l"
{ TOKEN(TOKEN_OR, "TOKEN_OR"); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 58 "smart_home.l"
{ TOKEN(TOKEN_NOT, "TOKEN_NOT"); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 60 "smart_home.l"
{
                    TOKEN(TOKEN_BOOL, "TOKEN_BOOL");
                }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 64 "smart_home.l"
{
                    TOKEN(TOKEN_MODO, "TOKEN_MODO");
                }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 68 "smart_home.l"
{
                    TOKEN(TOKEN_COLOR, "TOKEN_COLOR");
                }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 72 "smart_home.l"
{
                    TOKEN(TOKEN_ID_SENSOR_NUM, "TOKEN_ID_SENSOR_NUM");
                }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 76 "smart_home.l"
{
                    TOKEN(TOKEN_ID_SENSOR_BOOL, "TOKEN_ID_SENSOR_BOOL");
                }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 80 "smart_home.l"
{
                    TOKEN(TOKEN_ID_DISPOSITIVO, "TOKEN_ID_DISPOSITIVO");
                }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 84 "smart_home.l"
{
                    TOKEN(TOKEN_ID_DISPOSITIVO, "TOKEN_ID_DISPOSITIVO");
                }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 88 "smart_home.l"
{
                    TOKEN(TOKEN_ATRIBUTO, "TOKEN_ATRIBUTO");
                }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 92 "smart_home.l"
{ TOKEN(TOKEN_EMAIL, "TOKEN_EMAIL"); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 93 "smart_home.l"
{ TOKEN(TOKEN_TEXTO, "TOKEN_TEXTO"); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 94 "smart_home.l"
{ TOKEN(TOKEN_HORA, "TOKEN_HORA"); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 95 "smart_home.l"
{ TOKEN(TOKEN_FECHA, "TOKEN_FECHA"); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 96 "smart_home.l"
{ TOKEN(TOKEN_NUM_TEMP, "TOKEN_NUM_TEMP"); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 97 "smart_home.l"
{ TOKEN(TOKEN_PERCENT, "TOKEN_PERCENT"); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 98 "smart_home.l"
{ TOKEN(TOKEN_TIME, "TOKEN_TIME"); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 99 "smart_home.l"
{ TOKEN(TOKEN_LUX, "TOKEN_LUX"); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 100 "smart_home.l"
{ TOKEN(TOKEN_NUMERO, "TOKEN_NUMERO"); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 102 "smart_home.l"
{ TOKEN(TOKEN_IGUALDAD, "TOKEN_IGUALDAD"); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 103 "smart_home.l"
{ TOKEN(TOKEN_DIFERENTE, "TOKEN_DIFERENTE"); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 104 "smart_home.l"
{ TOKEN(TOKEN_MAYOR_IGUAL, "TOKEN_MAYOR_IGUAL"); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 105 "smart_home.l"
{ TOKEN(TOKEN_MENOR_IGUAL, "TOKEN_MENOR_IGUAL"); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 106 "smart_home.l"
{ TOKEN(TOKEN_IGUAL, "TOKEN_IGUAL"); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 107 "smart_home.l"
{ TOKEN(TOKEN_MAYOR, "TOKEN_MAYOR"); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 108 "smart_home.l"
{ TOKEN(TOKEN_MENOR, "TOKEN_MENOR"); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 109 "smart_home.l"
{ TOKEN(TOKEN_PUNTO, "TOKEN_PUNTO"); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 110 "smart_home.l"
{ TOKEN(TOKEN_PARENTESIS_ABRE, "TOKEN_PARENTESIS_ABRE"); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 111 "smart_home.l"
{ TOKEN(TOKEN_PARENTESIS_CIERRA, "TOKEN_PARENTESIS_CIERRA"); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 113 "smart_home.l"
{ TOKEN(TOKEN_ID, "TOKEN_ID"); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 115 "smart_home.l"
{
                    imprimir_token("TOKEN_ERROR", yytext);
                    printf("          [ERROR LEXICO] Simbolo no reconocido: %s\n", yytext);
                    errores_lexicos++;
                    return TOKEN_ERROR;
                }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 122 "smart_home.l"
ECHO;
	YY_BREAK
#line 1602 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 299 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 299 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 298);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 122 "smart_home.l"


#ifdef LEXER_STANDALONE
int main(int argc, char *argv[]) {
    printf("--- Lexer SMART-HOME simple ---\n");

    if (argc == 2) {
        yyin = fopen(argv[1], "r");
        if (yyin == NULL) {
            printf("[ERROR] No se pudo abrir el archivo: %s\n", argv[1]);
            return 1;
        }
    } else if (argc > 2) {
        printf("Uso: %s [archivo]\n", argv[0]);
        return 1;
    }

    while (yylex() != 0) {
    }

    if (yyin != NULL && yyin != stdin) {
        fclose(yyin);
    }

    if (errores_lexicos == 0) {
        printf("\nAnalisis lexico finalizado sin errores.\n");
    } else {
        printf("\nAnalisis lexico finalizado con %d error(es).\n", errores_lexicos);
    }

    return errores_lexicos == 0 ? 0 : 1;
}
#endif

