
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 42
#define YY_END_OF_BUFFER 43
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[292] =
    {   0,
        0,    0,   43,   41,    1,    1,   41,   41,   41,   38,
       39,   41,   37,   41,   29,   36,   34,   35,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,    1,   31,    0,   22,
        0,    0,   29,    2,   26,    0,   29,   25,   27,    0,
        0,   33,   30,   32,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,    8,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,    5,   40,   40,   40,
       40,   40,   13,   11,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,    0,    2,   29,    0,    0,

        0,    0,   40,   40,   40,   40,   10,   40,   40,   40,
       40,   40,   40,   40,   40,   40,    9,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   12,   13,   40,
       40,   15,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,    0,    0,    0,   28,   25,   40,   40,   40,
       40,   15,   40,   15,   40,   40,   40,   40,    7,   40,
       40,   40,   40,   40,   40,   14,   20,   40,   20,   20,
       40,   40,   40,   15,   40,   40,    6,   13,   14,   40,
        3,   40,    0,    0,   23,   40,   40,   40,   40,   40,
       40,   14,   40,   20,   20,   40,    4,   13,   20,   40,

       40,   40,   19,   40,   40,   40,   15,   21,    0,   40,
       18,   19,   40,   15,   20,   40,   40,   20,   40,   40,
       40,   40,   40,   40,   40,   21,    0,   40,   40,   40,
       40,   20,   40,   40,   40,   40,   40,   20,   21,    0,
       20,   40,   40,   40,   20,   40,   40,   40,   40,   20,
       20,    0,   40,   40,   40,   40,   40,   40,   40,   40,
       24,   40,   40,   16,   40,   40,   40,   40,   20,   40,
       17,   40,   16,   20,   40,   40,   40,   40,   40,   40,
       40,   40,   20,   16,   40,   40,   40,   16,   40,   17,
        0

    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    7,    1,    1,    8,
        9,    1,   10,    1,   11,   12,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   15,    1,   16,
       17,   18,    1,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   26,   30,   31,   32,   33,   34,
       26,   35,   36,   37,   38,   39,   40,   41,   42,   43,
        1,    1,    1,    1,   44,    1,   45,   46,   47,   48,

       49,   50,   26,   51,   52,   53,   26,   54,   55,   56,
       57,   58,   26,   59,   60,   61,   62,   63,   64,   41,
       65,   66,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   67,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   68,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[69] =
    {   0,
        1,    1,    2,    3,    1,    1,    4,    1,    1,    4,
        5,    5,    1,    5,    1,    1,    1,    1,    4,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    4,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    1,    1
    } ;

static const flex_int16_t yy_base[302] =
    {   0,
        0,    0,  234, 2171,   67,   70,  216,  224,  205, 2171,
     2171,   61,  197,  201,   74,  194,  193,  192,  136,   72,
      120,   80,  196,  253,   96,  140,  126,  174,  168,  257,
      271,  284,  230,  299,  312,  234,   74, 2171,  199, 2171,
      185,    0,  186,    0,  180,   75,  103,  177,  176,  151,
      127, 2171, 2171, 2171,  210,  320,  328,  352,  363,  381,
      389,  395,  405,  418,  419,  373,  429,  448,  459,  469,
      473,  484,  498,  506,  514,  492,  522,  536,  537,  551,
      552,  565,  584,  588,  592,  598,  609,  619,  623,  633,
      637,  655,  659,  670,  680,  179,    0,   71,  171,  168,

       78,   73,  691,  699,  695,  715,  721,  732,  740,  746,
      754,  764,  768,  781,  782,  792,  800,  806,  822,  823,
      833,  843,  854,  858,  878,  879,  894,  898,  909,  913,
      923,  927,  938,  946,  957,  970,  978,  989,  995,  999,
     1012, 1023,  100,  153,  148,  138, 2171, 1033, 1029, 1039,
     1043, 1047, 1057, 1068, 1078, 1079, 1100, 1106, 1114, 1124,
     1132, 1140, 1150, 1151, 1165, 1169, 1179, 1183, 1194, 1200,
     1204, 1208, 1214, 1227, 1228, 1238, 1252, 1253, 1267, 1268,
     1281, 1282,  149,  143, 2171, 1295, 1301, 1309, 1315, 1323,
     1331, 1339, 1350, 1356, 1364, 1372, 1380, 1390, 1394, 1404,

     1400, 1415, 1425, 1429, 1439, 1456, 1443,  160,  140, 1464,
     1479, 1483, 1487, 1497, 1501, 1507, 1522, 1521, 1532, 1536,
     1540, 1551, 1555, 1572, 1589,  207,  135, 1593, 1597, 1607,
     1613, 1617, 1637, 1621, 1676, 1648, 1652, 1668,  129,  121,
     1682, 1704, 1710, 1726, 1732, 1736, 1746, 1747, 1757, 1775,
     1776,  110, 1795, 1805, 1809, 1819, 1834, 1835, 1848, 1862,
     2171, 1870, 1884, 1894, 1900, 1915, 1925, 1919, 1938, 1944,
     1958, 1962, 1968, 1976, 1984, 1990, 1994, 2008, 2009, 2022,
     2043, 2042, 2061, 2065, 2069, 2075, 2083, 2096, 2097, 2107,
     2171, 2154, 2156, 2158,  118, 2163,  117,  104, 2165,   95,

       93
    } ;

static const flex_int16_t yy_def[302] =
    {   0,
      291,    1,  291,  291,  291,  291,  291,  292,  293,  291,
      291,  293,  293,  291,  293,  291,  291,  291,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  291,  291,  292,  291,
      293,  295,   15,  296,  293,  293,   15,  293,  293,  293,
      291,  291,  291,  291,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  295,  296,   15,  291,  291,

      293,  291,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  297,  291,  291,  293,  291,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  298,  291,  291,  294,  299,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,

      294,  294,  294,  294,  294,  294,  294,  300,  291,  294,
      299,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  301,  291,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  295,  291,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  291,  294,  294,  294,  294,  294,  294,  294,  294,
      291,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
        0,  291,  291,  291,  291,  291,  291,  291,  291,  291,

      291
    } ;

static const flex_int16_t yy_nxt[2240] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,    9,
       12,   13,   14,   15,    4,   16,   17,   18,    4,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   25,   25,
       28,   29,   30,   31,   32,   33,   34,   25,   35,   36,
       25,   25,   25,   25,   19,   20,   21,   22,   23,   24,
       26,   27,   25,   25,   28,   29,   30,   31,   32,   33,
       34,   25,   35,   36,   25,   25,    4,    4,   37,   37,
       37,   37,   37,   37,   43,   37,   37,   37,   41,   42,
       45,   41,   41,   41,   98,   46,   41,   47,   98,   41,
       42,   41,   42,   42,  147,   48,   42,  239,   42,  226,

       49,   61,   41,   50,   49,   41,   62,   41,  208,   49,
       96,  143,   66,   96,   42,   99,   43,  100,  146,  147,
       48,  183,   96,  261,   49,   61,   41,   50,   49,   41,
       62,   41,   41,   49,  252,   41,   66,   41,   42,   63,
      143,   51,   41,   64,   42,   41,   41,   41,  240,   41,
       77,   41,   65,  227,   42,  209,   42,   56,   42,   96,
      143,  185,   96,   57,   63,   58,  184,   59,   64,   42,
       96,  143,   76,   96,   41,   77,   65,   41,   60,   41,
       41,  145,   56,   41,  144,   41,   42,   57,  101,   58,
      143,   59,   42,  102,   42,   42,   76,   78,   42,   43,

       81,   60,   41,   42,   40,   41,   79,   41,   54,   53,
       52,   80,  101,   44,   42,   42,   41,   96,  143,   41,
       96,   41,   78,   42,   81,   67,   68,   69,   42,   40,
       79,   70,   38,  291,   71,   80,   41,  291,  291,   41,
       41,   41,  291,   41,  291,   41,  291,  291,   42,   67,
       68,   69,   42,   89,  291,   70,  291,  291,   71,   41,
       95,  291,   41,   41,   41,  291,   41,  291,   41,  291,
      291,   42,   72,  291,  291,   42,   73,   41,   89,  291,
       41,   82,   41,  291,   95,   74,  291,   75,   83,   42,
       41,   84,  291,   41,   85,   41,  291,   72,  291,  291,

      291,   73,   42,   86,  291,   41,   82,   87,   41,   74,
       41,   75,   83,  291,  291,   84,   88,   42,   41,   85,
      291,   41,   90,   41,  291,   91,   41,   86,  291,   41,
       42,   41,   87,   92,   41,   93,  291,   41,   42,   41,
       88,  291,  291,  291,   94,  291,   42,   90,  291,   91,
      291,  291,  291,  291,  291,  291,  103,   92,   41,  291,
       93,   41,  104,   41,  291,  291,  291,  291,   94,   41,
       42,  105,   41,  291,   41,  291,  291,  291,  291,   41,
      103,   42,   41,  291,   41,  107,  104,   41,  106,  291,
       41,   42,   41,  291,  291,   41,  105,  291,   41,   42,

       41,   41,  291,  291,   41,  291,   41,   42,  109,  291,
      107,   41,  106,   42,   41,  291,   41,  291,  108,  291,
      291,  291,  111,   42,   41,   41,  110,   41,   41,   41,
       41,  291,  291,  109,  112,   41,   42,   42,   41,  291,
       41,  291,  108,  291,  291,  291,  111,   42,  114,  291,
      110,  291,  113,  291,   41,  291,  291,   41,  112,   41,
      291,  291,  291,  291,  115,   41,   42,  116,   41,  291,
       41,  291,  114,  291,  291,   41,  113,   42,   41,   41,
       41,  117,   41,  291,   41,  291,  291,   42,  115,  291,
       41,   42,  116,   41,  291,   41,  119,  291,   41,  291,

      291,   41,   42,   41,   41,  118,  117,   41,  291,   41,
       42,  291,   41,  120,  291,   41,   42,   41,  291,  121,
       41,  119,  291,   41,   42,   41,  124,  122,   41,  118,
      291,   41,   42,   41,  291,  291,  291,  120,  291,  291,
       42,  123,   41,   41,  121,   41,   41,   41,   41,  291,
      124,  291,  122,  291,   42,   42,  291,   41,   41,  126,
       41,   41,   41,   41,  291,  123,  291,  125,  291,   42,
       42,   41,  291,  291,   41,  291,   41,  291,  291,  291,
      291,  291,  291,   42,  126,  291,  291,  127,  128,  129,
       41,  125,  291,   41,   41,   41,  291,   41,   41,   41,

      291,   41,   42,   41,   41,  291,   42,   41,  291,   41,
       42,  127,  128,  291,  129,   41,   42,  291,   41,  291,
       41,  291,  291,  291,  291,   41,  130,   42,   41,   41,
       41,  132,   41,  131,   41,  291,  291,   42,  133,   41,
      291,   42,   41,   41,   41,  291,   41,  134,   41,  291,
      130,   42,  291,  291,  135,   42,  132,  131,  291,  291,
      137,   41,  133,  136,   41,   41,   41,  291,   41,  291,
       41,  134,  291,   42,  291,  291,   41,   42,  135,   41,
      291,   41,  291,  291,  291,  137,   41,  136,   42,   41,
      139,   41,  138,  291,  291,  291,  291,   41,   42,  140,

       41,   41,   41,  141,   41,   41,   41,  142,   41,   42,
       41,  291,  291,   42,  139,  291,  138,   42,  148,  291,
      291,   41,  149,  140,   41,  291,   41,   41,  141,  150,
       41,  142,   41,   42,  151,  291,  291,  291,   41,   42,
      291,   41,  148,   41,  291,  291,   41,  149,  291,   41,
       42,   41,   41,  150,  291,   41,  291,   41,   42,  151,
       41,  152,  291,   41,   42,   41,  291,  291,  291,  154,
       41,  153,   42,   41,   41,   41,  291,   41,  291,   41,
      291,  291,   42,  155,  291,  152,   42,   41,   41,  291,
       41,   41,   41,   41,  154,  153,  156,  291,   41,   42,

       42,   41,  157,   41,  291,  159,   41,  155,  291,   41,
       42,   41,   41,  158,  291,   41,  291,   41,   42,  160,
      156,  291,  291,  291,   42,  161,  157,  291,   41,   41,
      159,   41,   41,   41,   41,  291,  291,  158,  291,   41,
       42,   42,   41,  160,   41,  291,  291,  291,  291,   41,
      161,   42,   41,  291,   41,  291,  162,  291,  163,  164,
       41,   42,  291,   41,   41,   41,  291,   41,  291,   41,
      291,  291,   42,  291,  291,  165,   42,  167,  291,  291,
      162,  291,  163,  164,   41,   41,  166,   41,   41,   41,
       41,  291,  291,  291,  291,  291,   42,   42,  291,  165,

       41,  291,  167,   41,   41,   41,  291,   41,  291,   41,
      166,  169,   42,  168,  291,   41,   42,  170,   41,   41,
       41,  291,   41,  291,   41,  291,  291,   42,  291,   41,
      291,   42,   41,   41,   41,  169,   41,  168,   41,  291,
      291,   42,  170,  291,   41,   42,  291,   41,  171,   41,
      172,  291,   41,  291,  291,   41,   42,   41,  291,  291,
      291,  291,  291,   41,   42,  291,   41,  291,   41,  291,
      173,  291,  171,  291,  172,   42,   41,  291,  174,   41,
      291,   41,  291,  291,   41,  291,  291,   41,   42,   41,
      291,  291,  175,  291,  173,   41,   42,  291,   41,  291,

       41,   41,  174,  176,   41,   41,   41,   42,   41,  177,
       41,  291,  178,   42,  291,  291,  175,   42,   41,  291,
      291,   41,  291,   41,  291,  291,  291,  176,  291,   41,
       42,  179,   41,  177,   41,   41,  180,  178,   41,   41,
       41,   42,   41,  181,   41,   41,  291,   42,   41,   41,
       41,   42,   41,   41,   41,  179,   41,   42,   41,  182,
      180,   42,  291,   41,  291,   42,   41,  181,   41,  188,
      291,  186,  187,  291,   41,   42,  291,   41,  190,   41,
      291,  189,  291,  182,   41,   41,   42,   41,   41,   41,
       41,  291,  291,  188,  291,  186,   42,   42,  291,  291,

      291,  291,  291,  190,  291,  189,   41,  191,  291,   41,
      291,   41,   41,  192,  291,   41,  291,   41,   42,  193,
       41,  291,  291,   41,   42,   41,  291,  291,  291,  291,
       41,  191,   42,   41,  291,   41,  291,  192,   41,  291,
      194,   41,   42,   41,  193,  291,   41,  291,  291,   41,
       42,   41,  291,  195,  196,  291,   41,   41,   42,   41,
       41,   41,   41,  291,  194,  291,  291,  291,   42,   42,
      199,   41,  291,  198,   41,   41,   41,  195,   41,  196,
       41,  197,  291,   42,  291,   41,  291,   42,   41,   41,
       41,  291,   41,  291,   41,  199,  291,   42,  198,  291,

       41,   42,  200,   41,  197,   41,   41,  291,  187,   41,
       41,   41,   42,   41,   41,   41,  291,   41,   42,   41,
       41,  291,   42,   41,  291,   41,   42,  200,  291,  202,
      291,  201,   42,   41,   41,  291,   41,   41,   41,   41,
      291,  291,  203,  291,   41,   42,   42,   41,  291,   41,
      291,  291,  291,  291,  202,  201,   42,  291,   41,   41,
      204,   41,   41,   41,   41,  291,  203,  291,  291,  291,
       42,   42,  291,   41,   41,  291,   41,   41,   41,   41,
      291,  205,  291,  291,  204,   42,   42,   41,   41,  291,
       41,   41,   41,   41,  291,  291,  291,  291,  206,   42,

       42,   41,  291,  291,   41,  207,   41,   41,  291,  291,
       41,  291,   41,   42,  210,   41,  291,  291,   41,   42,
       41,   41,  206,  291,   41,  291,   41,   42,  212,   41,
      207,  291,   41,   42,   41,  291,  291,   41,  291,  210,
       41,   42,   41,  291,  291,   41,  291,  213,   41,   42,
       41,  291,  291,  212,  291,  214,   41,   42,  291,   41,
      291,   41,   41,  215,  291,   41,  291,   41,   42,  291,
       41,  213,  216,   41,   42,   41,  291,  291,   41,  214,
      291,   41,   42,   41,  291,  291,   41,  215,  291,   41,
       42,   41,  291,  291,  291,  291,   41,  216,   42,   41,

       41,   41,  291,   41,  218,   41,   41,  217,   42,   41,
       41,   41,   42,   41,  291,   41,  291,  291,   42,  220,
      291,   41,   42,  291,   41,  291,   41,  291,  218,  291,
      291,   41,  219,   42,   41,   41,   41,  291,   41,  291,
       41,  291,  221,   42,  220,   41,  291,   42,   41,   41,
       41,  291,   41,  291,   41,  291,  219,   42,  223,  291,
      291,   42,   41,  222,  291,   41,  221,   41,  187,  291,
       41,  224,  291,   41,   42,   41,  291,  291,  291,  225,
      291,  291,   42,  223,  291,   41,  228,  222,   41,   41,
       41,  291,   41,   41,   41,  224,   41,   42,   41,  291,

      291,   42,  291,   41,  225,   42,   41,   41,   41,  291,
       41,  228,   41,   41,  291,   42,   41,  291,   41,   42,
      291,  291,  291,  291,  291,   42,  187,   41,   41,  229,
       41,   41,   41,   41,  291,  291,  291,  291,   41,   42,
       42,   41,   41,   41,  230,   41,   41,   41,  291,   41,
       42,   41,  229,  231,   42,  232,  291,   41,   42,  291,
       41,   41,   41,  291,   41,  291,   41,  233,  230,   42,
      291,  291,  234,   42,  291,  291,  236,  231,   41,  291,
      232,   41,  291,   41,  291,  291,  291,  291,  291,  291,
       42,  233,  237,  291,  235,   41,  234,  291,   41,   41,

       41,  236,   41,   41,   41,  291,   41,   42,   41,  291,
      291,   42,  241,   41,  291,   42,   41,  237,   41,   41,
      238,  291,   41,   41,   41,   42,   41,   41,   41,  291,
       41,   42,   41,  291,  291,   42,  291,  241,  291,   42,
      187,  242,  291,   41,  238,  243,   41,  291,   41,  291,
      291,  291,  245,  291,   41,   42,  244,   41,   41,   41,
      291,   41,  291,   41,  291,  242,   42,  291,  291,  243,
       42,  291,  291,  291,   41,  291,  245,   41,  291,   41,
      251,  244,   41,  291,  250,   41,   42,   41,   41,  291,
      291,   41,  291,   41,   42,  291,  291,  291,  291,  291,

       42,  291,  246,  291,  251,  247,  248,  291,  250,  291,
       41,  291,  249,   41,  291,   41,   41,  291,  291,   41,
      291,   41,   42,  253,  291,  291,  246,  291,   42,  247,
      248,  291,   41,  291,  291,   41,  249,   41,   41,  291,
      291,   41,   41,   41,   42,   41,  254,   41,  253,  291,
       42,  291,   41,   41,   42,   41,   41,   41,   41,  291,
      291,  291,  291,   41,   42,   42,   41,  291,   41,  187,
      254,  291,  291,  255,  291,   42,  291,  291,  291,  257,
      258,   41,   41,  256,   41,   41,   41,   41,  291,  291,
      291,  291,  291,   42,   42,  291,  291,  255,  291,  260,

      291,   41,  291,  257,   41,  258,   41,  256,  291,  291,
      291,   41,  259,   42,   41,   41,   41,  291,   41,  291,
       41,  291,  291,   42,  260,   41,  291,   42,   41,  291,
       41,  291,  262,  291,  291,  291,  259,   42,  187,  263,
       41,   41,  291,   41,   41,   41,   41,  291,  291,  291,
      291,  291,   42,   42,   41,  291,  262,   41,  291,   41,
      291,  264,  291,  263,  291,  266,   42,  267,   41,  291,
      291,   41,  265,   41,  291,  291,   41,  291,  291,   41,
       42,   41,  291,  291,  264,  291,  291,  291,   42,  266,
       41,  291,  267,   41,  269,   41,  265,  291,  268,  291,

       41,  291,   42,   41,  291,   41,   41,  270,  291,   41,
      291,   41,   42,  291,  291,  291,  271,  291,   42,  269,
      291,   41,  268,  291,   41,   41,   41,  272,   41,  291,
       41,   41,  270,   42,   41,  291,   41,   42,  291,  291,
      271,  291,  291,   42,   41,  291,  275,   41,  273,   41,
       41,  272,  291,   41,  274,   41,   42,  291,  291,  291,
      291,  291,   42,  291,   41,  291,  276,   41,   41,   41,
      275,   41,  273,   41,   41,  291,   42,   41,  274,   41,
       42,  291,   41,  291,  291,   41,   42,   41,  291,  291,
       41,  276,  277,   41,   42,   41,   41,  291,  291,   41,

       41,   41,   42,   41,  291,   41,  291,  291,   42,  280,
      291,  278,   42,  291,   41,   41,  277,   41,   41,   41,
       41,  281,  279,  291,  291,  291,   42,   42,   41,  291,
      291,   41,  291,   41,  280,  282,  291,  291,  291,  291,
       42,  283,  291,  291,  284,  281,  279,  291,   41,   41,
      291,   41,   41,   41,   41,  291,  291,  291,  291,  282,
       42,   42,  291,  291,  291,  283,  285,   41,  291,  284,
       41,   41,   41,  286,   41,   41,   41,  291,   41,   42,
       41,   41,  291,   42,   41,  291,   41,   42,  291,   41,
      291,  285,   41,   42,   41,  291,  291,  286,  291,  291,

      287,   42,   41,   41,  291,   41,   41,   41,   41,  291,
      291,  288,  291,   41,   42,   42,   41,  291,   41,  289,
      291,  291,  291,  291,  287,   42,  291,  291,  291,  290,
      291,  291,  291,  291,  291,  288,  291,  291,  291,  291,
      291,  291,  291,  289,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  290,   39,  291,  291,   39,   39,   41,
       41,   55,   55,   97,  291,   97,   97,   97,  211,  211,
        3,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,

      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291
    } ;

static const flex_int16_t yy_chk[2240] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    5,    5,
        5,    6,    6,    6,   12,   37,   37,   37,   20,   12,
       15,   20,   98,   20,   98,   15,   22,   15,   46,   22,
       20,   22,   15,   46,  102,   15,  101,  301,   22,  300,

       15,   20,   25,   15,   15,   25,   20,   25,  298,   15,
      143,  143,   22,  143,   25,   47,   47,   47,  101,  102,
       15,  297,  295,  252,   15,   20,   21,   15,   15,   21,
       20,   21,   27,   15,  240,   27,   22,   27,   21,   21,
      239,   15,   19,   21,   27,   19,   26,   19,  227,   26,
       27,   26,   21,  209,   19,  184,  146,   19,   26,  183,
      183,  145,  183,   19,   21,   19,  144,   19,   21,   50,
      208,  208,   26,  208,   29,   27,   21,   29,   19,   29,
       28,  100,   19,   28,   99,   28,   29,   19,   50,   19,
       96,   19,   28,   51,   49,   48,   26,   28,   45,   43,

       29,   19,   23,   41,   39,   23,   28,   23,   18,   17,
       16,   28,   50,   14,   23,   13,   55,  226,  226,   55,
      226,   55,   28,    9,   29,   23,   23,   23,   55,    8,
       28,   23,    7,    3,   23,   28,   33,    0,    0,   33,
       36,   33,    0,   36,    0,   36,    0,    0,   33,   23,
       23,   23,   36,   33,    0,   23,    0,    0,   23,   24,
       36,    0,   24,   30,   24,    0,   30,    0,   30,    0,
        0,   24,   24,    0,    0,   30,   24,   31,   33,    0,
       31,   30,   31,    0,   36,   24,    0,   24,   30,   31,
       32,   30,    0,   32,   31,   32,    0,   24,    0,    0,

        0,   24,   32,   31,    0,   34,   30,   32,   34,   24,
       34,   24,   30,    0,    0,   30,   32,   34,   35,   31,
        0,   35,   34,   35,    0,   34,   56,   31,    0,   56,
       35,   56,   32,   34,   57,   35,    0,   57,   56,   57,
       32,    0,    0,    0,   35,    0,   57,   34,    0,   34,
        0,    0,    0,    0,    0,    0,   56,   34,   58,    0,
       35,   58,   57,   58,    0,    0,    0,    0,   35,   59,
       58,   58,   59,    0,   59,    0,    0,    0,    0,   66,
       56,   59,   66,    0,   66,   59,   57,   60,   58,    0,
       60,   66,   60,    0,    0,   61,   58,    0,   61,   60,

       61,   62,    0,    0,   62,    0,   62,   61,   61,    0,
       59,   63,   58,   62,   63,    0,   63,    0,   60,    0,
        0,    0,   62,   63,   64,   65,   61,   64,   65,   64,
       65,    0,    0,   61,   63,   67,   64,   65,   67,    0,
       67,    0,   60,    0,    0,    0,   62,   67,   65,    0,
       61,    0,   64,    0,   68,    0,    0,   68,   63,   68,
        0,    0,    0,    0,   67,   69,   68,   68,   69,    0,
       69,    0,   65,    0,    0,   70,   64,   69,   70,   71,
       70,   69,   71,    0,   71,    0,    0,   70,   67,    0,
       72,   71,   68,   72,    0,   72,   71,    0,   76,    0,

        0,   76,   72,   76,   73,   70,   69,   73,    0,   73,
       76,    0,   74,   72,    0,   74,   73,   74,    0,   73,
       75,   71,    0,   75,   74,   75,   76,   74,   77,   70,
        0,   77,   75,   77,    0,    0,    0,   72,    0,    0,
       77,   75,   78,   79,   73,   78,   79,   78,   79,    0,
       76,    0,   74,    0,   78,   79,    0,   80,   81,   79,
       80,   81,   80,   81,    0,   75,    0,   78,    0,   80,
       81,   82,    0,    0,   82,    0,   82,    0,    0,    0,
        0,    0,    0,   82,   79,    0,    0,   80,   81,   82,
       83,   78,    0,   83,   84,   83,    0,   84,   85,   84,

        0,   85,   83,   85,   86,    0,   84,   86,    0,   86,
       85,   80,   81,    0,   82,   87,   86,    0,   87,    0,
       87,    0,    0,    0,    0,   88,   85,   87,   88,   89,
       88,   87,   89,   86,   89,    0,    0,   88,   87,   90,
        0,   89,   90,   91,   90,    0,   91,   88,   91,    0,
       85,   90,    0,    0,   89,   91,   87,   86,    0,    0,
       91,   92,   87,   90,   92,   93,   92,    0,   93,    0,
       93,   88,    0,   92,    0,    0,   94,   93,   89,   94,
        0,   94,    0,    0,    0,   91,   95,   90,   94,   95,
       93,   95,   92,    0,    0,    0,    0,  103,   95,   94,

      103,  105,  103,   95,  105,  104,  105,   95,  104,  103,
      104,    0,    0,  105,   93,    0,   92,  104,  103,    0,
        0,  106,  104,   94,  106,    0,  106,  107,   95,  105,
      107,   95,  107,  106,  106,    0,    0,    0,  108,  107,
        0,  108,  103,  108,    0,    0,  109,  104,    0,  109,
      108,  109,  110,  105,    0,  110,    0,  110,  109,  106,
      111,  108,    0,  111,  110,  111,    0,    0,    0,  110,
      112,  109,  111,  112,  113,  112,    0,  113,    0,  113,
        0,    0,  112,  111,    0,  108,  113,  114,  115,    0,
      114,  115,  114,  115,  110,  109,  112,    0,  116,  114,

      115,  116,  113,  116,    0,  115,  117,  111,    0,  117,
      116,  117,  118,  114,    0,  118,    0,  118,  117,  116,
      112,    0,    0,    0,  118,  118,  113,    0,  119,  120,
      115,  119,  120,  119,  120,    0,    0,  114,    0,  121,
      119,  120,  121,  116,  121,    0,    0,    0,    0,  122,
      118,  121,  122,    0,  122,    0,  119,    0,  120,  121,
      123,  122,    0,  123,  124,  123,    0,  124,    0,  124,
        0,    0,  123,    0,    0,  122,  124,  124,    0,    0,
      119,    0,  120,  121,  125,  126,  123,  125,  126,  125,
      126,    0,    0,    0,    0,    0,  125,  126,    0,  122,

      127,    0,  124,  127,  128,  127,    0,  128,    0,  128,
      123,  126,  127,  125,    0,  129,  128,  127,  129,  130,
      129,    0,  130,    0,  130,    0,    0,  129,    0,  131,
        0,  130,  131,  132,  131,  126,  132,  125,  132,    0,
        0,  131,  127,    0,  133,  132,    0,  133,  130,  133,
      131,    0,  134,    0,    0,  134,  133,  134,    0,    0,
        0,    0,    0,  135,  134,    0,  135,    0,  135,    0,
      133,    0,  130,    0,  131,  135,  136,    0,  134,  136,
        0,  136,    0,    0,  137,    0,    0,  137,  136,  137,
        0,    0,  135,    0,  133,  138,  137,    0,  138,    0,

      138,  139,  134,  136,  139,  140,  139,  138,  140,  137,
      140,    0,  138,  139,    0,    0,  135,  140,  141,    0,
        0,  141,    0,  141,    0,    0,    0,  136,    0,  142,
      141,  139,  142,  137,  142,  149,  140,  138,  149,  148,
      149,  142,  148,  141,  148,  150,    0,  149,  150,  151,
      150,  148,  151,  152,  151,  139,  152,  150,  152,  142,
      140,  151,    0,  153,    0,  152,  153,  141,  153,  150,
        0,  148,  149,    0,  154,  153,    0,  154,  153,  154,
        0,  151,    0,  142,  155,  156,  154,  155,  156,  155,
      156,    0,    0,  150,    0,  148,  155,  156,    0,    0,

        0,    0,    0,  153,    0,  151,  157,  155,    0,  157,
        0,  157,  158,  156,    0,  158,    0,  158,  157,  157,
      159,    0,    0,  159,  158,  159,    0,    0,    0,    0,
      160,  155,  159,  160,    0,  160,    0,  156,  161,    0,
      158,  161,  160,  161,  157,    0,  162,    0,    0,  162,
      161,  162,    0,  160,  161,    0,  163,  164,  162,  163,
      164,  163,  164,    0,  158,    0,    0,    0,  163,  164,
      164,  165,    0,  163,  165,  166,  165,  160,  166,  161,
      166,  162,    0,  165,    0,  167,    0,  166,  167,  168,
      167,    0,  168,    0,  168,  164,    0,  167,  163,    0,

      169,  168,  168,  169,  162,  169,  170,    0,  165,  170,
      171,  170,  169,  171,  172,  171,    0,  172,  170,  172,
      173,    0,  171,  173,    0,  173,  172,  168,    0,  172,
        0,  171,  173,  174,  175,    0,  174,  175,  174,  175,
        0,    0,  173,    0,  176,  174,  175,  176,    0,  176,
        0,    0,    0,    0,  172,  171,  176,    0,  177,  178,
      175,  177,  178,  177,  178,    0,  173,    0,    0,    0,
      177,  178,    0,  179,  180,    0,  179,  180,  179,  180,
        0,  176,    0,    0,  175,  179,  180,  181,  182,    0,
      181,  182,  181,  182,    0,    0,    0,    0,  180,  181,

      182,  186,    0,    0,  186,  182,  186,  187,    0,    0,
      187,    0,  187,  186,  186,  188,    0,    0,  188,  187,
      188,  189,  180,    0,  189,    0,  189,  188,  188,  190,
      182,    0,  190,  189,  190,    0,    0,  191,    0,  186,
      191,  190,  191,    0,    0,  192,    0,  189,  192,  191,
      192,    0,    0,  188,    0,  190,  193,  192,    0,  193,
        0,  193,  194,  191,    0,  194,    0,  194,  193,    0,
      195,  189,  193,  195,  194,  195,    0,    0,  196,  190,
        0,  196,  195,  196,    0,    0,  197,  191,    0,  197,
      196,  197,    0,    0,    0,    0,  198,  193,  197,  198,

      199,  198,    0,  199,  196,  199,  201,  195,  198,  201,
      200,  201,  199,  200,    0,  200,    0,    0,  201,  201,
        0,  202,  200,    0,  202,    0,  202,    0,  196,    0,
        0,  203,  200,  202,  203,  204,  203,    0,  204,    0,
      204,    0,  202,  203,  201,  205,    0,  204,  205,  207,
      205,    0,  207,    0,  207,    0,  200,  205,  205,    0,
        0,  207,  206,  204,    0,  206,  202,  206,  203,    0,
      210,  205,    0,  210,  206,  210,    0,    0,    0,  206,
        0,    0,  210,  205,    0,  211,  210,  204,  211,  212,
      211,    0,  212,  213,  212,  205,  213,  211,  213,    0,

        0,  212,    0,  214,  206,  213,  214,  215,  214,    0,
      215,  210,  215,  216,    0,  214,  216,    0,  216,  215,
        0,    0,    0,    0,    0,  216,  212,  218,  217,  213,
      218,  217,  218,  217,    0,    0,    0,    0,  219,  218,
      217,  219,  220,  219,  216,  220,  221,  220,    0,  221,
      219,  221,  213,  217,  220,  219,    0,  222,  221,    0,
      222,  223,  222,    0,  223,    0,  223,  220,  216,  222,
        0,    0,  221,  223,    0,    0,  223,  217,  224,    0,
      219,  224,    0,  224,    0,    0,    0,    0,    0,    0,
      224,  220,  224,    0,  222,  225,  221,    0,  225,  228,

      225,  223,  228,  229,  228,    0,  229,  225,  229,    0,
        0,  228,  228,  230,    0,  229,  230,  224,  230,  231,
      225,    0,  231,  232,  231,  230,  232,  234,  232,    0,
      234,  231,  234,    0,    0,  232,    0,  228,    0,  234,
      229,  230,    0,  233,  225,  231,  233,    0,  233,    0,
        0,    0,  234,    0,  236,  233,  233,  236,  237,  236,
        0,  237,    0,  237,    0,  230,  236,    0,    0,  231,
      237,    0,    0,    0,  238,    0,  234,  238,    0,  238,
      237,  233,  235,    0,  236,  235,  238,  235,  241,    0,
        0,  241,    0,  241,  235,    0,    0,    0,    0,    0,

      241,    0,  235,    0,  237,  235,  235,    0,  236,    0,
      242,    0,  235,  242,    0,  242,  243,    0,    0,  243,
        0,  243,  242,  242,    0,    0,  235,    0,  243,  235,
      235,    0,  244,    0,    0,  244,  235,  244,  245,    0,
        0,  245,  246,  245,  244,  246,  243,  246,  242,    0,
      245,    0,  247,  248,  246,  247,  248,  247,  248,    0,
        0,    0,    0,  249,  247,  248,  249,    0,  249,  244,
      243,    0,    0,  246,    0,  249,    0,    0,    0,  248,
      249,  250,  251,  247,  250,  251,  250,  251,    0,    0,
        0,    0,    0,  250,  251,    0,    0,  246,    0,  251,

        0,  253,    0,  248,  253,  249,  253,  247,    0,    0,
        0,  254,  250,  253,  254,  255,  254,    0,  255,    0,
      255,    0,    0,  254,  251,  256,    0,  255,  256,    0,
      256,    0,  254,    0,    0,    0,  250,  256,  253,  255,
      257,  258,    0,  257,  258,  257,  258,    0,    0,    0,
        0,    0,  257,  258,  259,    0,  254,  259,    0,  259,
        0,  256,    0,  255,    0,  258,  259,  259,  260,    0,
        0,  260,  257,  260,    0,    0,  262,    0,    0,  262,
      260,  262,    0,    0,  256,    0,    0,    0,  262,  258,
      263,    0,  259,  263,  262,  263,  257,    0,  260,    0,

      264,    0,  263,  264,    0,  264,  265,  263,    0,  265,
        0,  265,  264,    0,    0,    0,  263,    0,  265,  262,
        0,  266,  260,    0,  266,  268,  266,  265,  268,    0,
      268,  267,  263,  266,  267,    0,  267,  268,    0,    0,
      263,    0,    0,  267,  269,    0,  268,  269,  266,  269,
      270,  265,    0,  270,  267,  270,  269,    0,    0,    0,
        0,    0,  270,    0,  271,    0,  270,  271,  272,  271,
      268,  272,  266,  272,  273,    0,  271,  273,  267,  273,
      272,    0,  274,    0,    0,  274,  273,  274,    0,    0,
      275,  270,  272,  275,  274,  275,  276,    0,    0,  276,

      277,  276,  275,  277,    0,  277,    0,    0,  276,  276,
        0,  273,  277,    0,  278,  279,  272,  278,  279,  278,
      279,  277,  275,    0,    0,    0,  278,  279,  280,    0,
        0,  280,    0,  280,  276,  278,    0,    0,    0,    0,
      280,  279,    0,    0,  280,  277,  275,    0,  282,  281,
        0,  282,  281,  282,  281,    0,    0,    0,    0,  278,
      282,  281,    0,    0,    0,  279,  281,  283,    0,  280,
      283,  284,  283,  282,  284,  285,  284,    0,  285,  283,
      285,  286,    0,  284,  286,    0,  286,  285,    0,  287,
        0,  281,  287,  286,  287,    0,    0,  282,    0,    0,

      285,  287,  288,  289,    0,  288,  289,  288,  289,    0,
        0,  286,    0,  290,  288,  289,  290,    0,  290,  287,
        0,    0,    0,    0,  285,  290,    0,    0,    0,  289,
        0,    0,    0,    0,    0,  286,    0,    0,    0,    0,
        0,    0,    0,  287,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  289,  292,    0,    0,  292,  292,  293,
      293,  294,  294,  296,    0,  296,  296,  296,  299,  299,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,

      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[43] =
    {   0,
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "smart_home.l"
/* Lexer SMART-HOME en formato Flex (.l).
   Genera un analizador lexico equivalente al lexer manual del proyecto. */
#define YY_NO_INPUT 1
#line 11 "smart_home.l"
#include <stdio.h>
#include <stdlib.h>

static int errores = 0;

static void imprimir_token(const char *tipo, const char *valor) {
    printf("Linea %-3d | %-24s | %s\n", yylineno, tipo, valor);
}

static void imprimir_error(const char *valor) {
    imprimir_token("TOKEN_ERROR", valor);
    printf("          [ERROR LEXICO] Simbolo o cadena no reconocida: %s\n", valor);
    errores++;
}
#line 1081 "lex.yy.c"
#line 1082 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 40 "smart_home.l"


#line 1300 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 292 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 2171 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 42 "smart_home.l"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 43 "smart_home.l"
;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 45 "smart_home.l"
{ imprimir_token("TOKEN_WHEN", yytext); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 46 "smart_home.l"
{ imprimir_token("TOKEN_EVERY", yytext); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 47 "smart_home.l"
{ imprimir_token("TOKEN_IF", yytext); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 48 "smart_home.l"
{ imprimir_token("TOKEN_THEN", yytext); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 49 "smart_home.l"
{ imprimir_token("TOKEN_ELSE", yytext); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 50 "smart_home.l"
{ imprimir_token("TOKEN_DO", yytext); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 51 "smart_home.l"
{ imprimir_token("TOKEN_END", yytext); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 52 "smart_home.l"
{ imprimir_token("TOKEN_AND", yytext); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 53 "smart_home.l"
{ imprimir_token("TOKEN_OR", yytext); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 54 "smart_home.l"
{ imprimir_token("TOKEN_NOT", yytext); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 56 "smart_home.l"
{
                            imprimir_token("TOKEN_BOOL", yytext);
                        }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 60 "smart_home.l"
{ imprimir_token("TOKEN_MODO", yytext); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 61 "smart_home.l"
{
                            imprimir_token("TOKEN_COLOR", yytext);
                        }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 65 "smart_home.l"
{
                            imprimir_token("TOKEN_ID_SENSOR_NUM", yytext);
                        }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 69 "smart_home.l"
{
                            imprimir_token("TOKEN_ID_SENSOR_BOOL", yytext);
                        }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 73 "smart_home.l"
{
                            imprimir_token("TOKEN_ID_DISPOSITIVO", yytext);
                        }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 76 "smart_home.l"
{ imprimir_token("TOKEN_ID_DISPOSITIVO", yytext); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 78 "smart_home.l"
{
                            imprimir_token("TOKEN_ATRIBUTO", yytext);
                        }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 82 "smart_home.l"
{ imprimir_token("TOKEN_EMAIL", yytext); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 83 "smart_home.l"
{ imprimir_token("TOKEN_TEXTO", yytext); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 84 "smart_home.l"
{ imprimir_token("TOKEN_HORA", yytext); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 85 "smart_home.l"
{ imprimir_token("TOKEN_FECHA", yytext); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 86 "smart_home.l"
{ imprimir_token("TOKEN_NUM_TEMP", yytext); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 87 "smart_home.l"
{ imprimir_token("TOKEN_PERCENT", yytext); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 88 "smart_home.l"
{ imprimir_token("TOKEN_TIME", yytext); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 89 "smart_home.l"
{ imprimir_token("TOKEN_LUX", yytext); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 90 "smart_home.l"
{ imprimir_token("TOKEN_NUMERO", yytext); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 92 "smart_home.l"
{ imprimir_token("TOKEN_IGUALDAD", yytext); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 93 "smart_home.l"
{ imprimir_token("TOKEN_DIFERENTE", yytext); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 94 "smart_home.l"
{ imprimir_token("TOKEN_MAYOR_IGUAL", yytext); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 95 "smart_home.l"
{ imprimir_token("TOKEN_MENOR_IGUAL", yytext); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 96 "smart_home.l"
{ imprimir_token("TOKEN_IGUAL", yytext); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 97 "smart_home.l"
{ imprimir_token("TOKEN_MAYOR", yytext); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 98 "smart_home.l"
{ imprimir_token("TOKEN_MENOR", yytext); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 99 "smart_home.l"
{ imprimir_token("TOKEN_PUNTO", yytext); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 100 "smart_home.l"
{ imprimir_token("TOKEN_PARENTESIS_ABRE", yytext); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 101 "smart_home.l"
{ imprimir_token("TOKEN_PARENTESIS_CIERRA", yytext); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 103 "smart_home.l"
{ imprimir_token("TOKEN_ID", yytext); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 104 "smart_home.l"
{ imprimir_error(yytext); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 106 "smart_home.l"
ECHO;
	YY_BREAK
#line 1590 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 292 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 292 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 291);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 106 "smart_home.l"


int main(int argc, char *argv[]) {
    printf("--- Lexer SMART-HOME: reconocimiento de tokens ---\n");

    if (argc == 2) {
        yyin = fopen(argv[1], "r");
        if (yyin == NULL) {
            printf("[ERROR] No se pudo abrir el archivo: %s\n", argv[1]);
            return 1;
        }
    } else if (argc > 2) {
        printf("Uso: %s [archivo]\n", argv[0]);
        return 1;
    }

    yylex();

    if (yyin != NULL && yyin != stdin) {
        fclose(yyin);
    }

    if (errores == 0) {
        printf("\nAnalisis lexico finalizado sin errores.\n");
    } else {
        printf("\nAnalisis lexico finalizado con %d error(es).\n", errores);
    }

    return errores == 0 ? 0 : 1;
}

