#line 1 "lex.parser.c"

#line 3 "lex.parser.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 46
#define YY_END_OF_BUFFER 47
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[305] =
    {   0,
        0,    0,   47,   45,    1,    1,   45,   45,   45,   41,
       42,   45,   40,   45,   32,   39,   37,   38,   44,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   45,    1,   34,
        0,   23,    0,    0,   32,    2,   28,    0,   32,   31,
       27,   29,   31,   31,   31,   36,   33,   35,   22,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
        8,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,    5,   43,   43,   43,   43,   43,   13,   11,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,

        0,   22,    2,   31,   31,   32,    0,    0,   31,   31,
       43,   43,   43,   43,   10,   43,   43,   43,   43,   43,
       43,   43,   43,   43,    9,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   12,   13,   43,   43,   15,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
        0,   22,    0,    0,   30,   27,   43,   43,   43,   43,
       15,   43,   15,   43,   43,   43,   43,    7,   43,   43,
       43,   43,   43,   43,   14,   20,   43,   20,   20,   43,
       43,   43,   15,   43,   43,    6,   13,   14,   43,    3,
       43,    0,    0,   22,    0,   25,   43,   43,   43,   43,

       43,   43,   14,   43,   20,   20,   43,    4,   13,   20,
       43,   43,   43,   19,   43,   43,   43,   15,    0,   21,
        0,   43,   18,   19,   43,   15,   20,   43,   43,   20,
       43,   43,   43,   43,   43,   43,   43,   24,   21,    0,
       43,   43,   43,   43,   20,   43,   43,   43,   43,   43,
       20,   21,    0,   20,   43,   43,   43,   20,   43,   43,
       43,   43,   20,   20,    0,   43,   43,   43,   43,   43,
       43,   43,   43,   26,   43,   43,   16,   43,   43,   43,
       43,   20,   43,   17,   43,   16,   20,   43,   43,   43,
       43,   43,   43,   43,   43,   20,   16,   43,   43,   43,

       16,   43,   17,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    7,    1,    1,    8,
        9,    1,   10,    1,   11,   12,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   15,    1,   16,
       17,   18,    1,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   26,   30,   31,   32,   33,   34,
       26,   35,   36,   37,   38,   39,   40,   41,   42,   43,
        1,    1,    1,    1,   44,    1,   45,   46,   47,   48,

       49,   50,   26,   51,   52,   53,   26,   54,   55,   56,
       57,   58,   26,   59,   60,   61,   62,   63,   64,   41,
       65,   66,    1,    1,    1,    1,    1,   67,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   68,   69,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   70,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   71,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   72,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[73] =
    {   0,
        1,    2,    3,    4,    2,    2,    5,    2,    2,    6,
        6,    6,    1,    5,    1,    2,    2,    2,    6,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    6,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    7,    1,    7,    8,
        8,    1
    } ;

static const flex_int16_t yy_base[320] =
    {   0,
        0,    0,  178, 2535,   71,   74,  157,  164,  150, 2535,
     2535,   65,  149,  154,   78,  149,  147,  146,    0,  143,
      100,  127,   84,  203,  260,   92,  170,  133,  181,  241,
      271,  275,  304,  213,  319,  332,  237,   94,   78, 2535,
      151, 2535,  137,  389,  455,    0,  347,   79,  100,  361,
      365,  375,  410,    0,   74, 2535, 2535, 2535,    0,  303,
      388,  404,  431,  488,  509,  510,  525,  531,  539,  550,
      477,  556,  569,  583,  584,  598,  608,  618,  622,  636,
      642,  656,  660,  664,  674,  684,  688,  698,  708,  712,
      718,  729,  739,  743,  753,  757,  775,  779,  790,  800,

       74,  852,    0,  804,    0,  104,  122,  117,  819,   73,
      866,  876,  872,  835,  815,  896,  920,  892,  926,  930,
      936,  950,  954,  958,  972,  978,  982,  992, 1002, 1006,
     1012, 1023, 1037, 1047, 1060, 1064, 1075, 1079, 1083, 1089,
     1093, 1109, 1110, 1124, 1137, 1141, 1152, 1165, 1166, 1187,
       56, 1248,  113,  112, 1176,    0, 1202, 1198, 1219, 1218,
     1233, 1261, 1265, 1275, 1279, 1283, 1314, 1294, 1315, 1329,
     1325, 1344, 1352, 1368, 1369, 1379, 1389, 1395, 1403, 1409,
     1413, 1417, 1431, 1432, 1447, 1457, 1461, 1465, 1471, 1475,
     1485,   52,   56, 1534,  108, 2535, 1486, 1500, 1510, 1504,

     1550, 1556, 1560, 1574, 1575, 1602, 1608, 1616, 1624, 1630,
     1638, 1644, 1659, 1663, 1667, 1673, 1689, 1693,   37, 1738,
       87, 1710, 1709, 1724, 1752, 1725, 1753, 1766, 1767, 1777,
     1805, 1781, 1815, 1823, 1831, 1837, 1845, 2535, 1901,   73,
     1861, 1875, 1888, 1917, 1918, 1932, 1946, 1996, 1973, 1947,
     1936,    0,   72, 1972, 1997, 2012, 1986, 2025, 2029, 2033,
     2046, 2056, 2062, 2077,   69, 2078, 2092, 2100, 2106, 2120,
     2126, 2141, 2155, 2535, 2159, 2163, 2178, 2191, 2192, 2211,
     2217, 2221, 2225, 2239, 2245, 2249, 2260, 2268, 2276, 2282,
     2292, 2296, 2307, 2326, 2330, 2306, 2344, 2357, 2358, 2371,

     2372, 2387, 2386, 2535, 2444, 2448, 2450, 2458, 2462, 2468,
     2476, 2480, 2484, 2492, 2500, 2508, 2512, 2518, 2526
    } ;

static const flex_int16_t yy_def[320] =
    {   0,
      304,    1,  304,  304,  304,  304,  304,  305,  306,  304,
      304,  306,  306,  304,  307,  304,  304,  304,  308,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  304,  304,  304,
      305,  304,  306,  310,  307,  311,  312,  306,   45,  312,
      312,  312,  312,  313,  313,  304,  304,  304,  308,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,

      304,  310,  311,  312,  313,   45,  304,  304,  312,  313,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      314,  315,  304,  304,  312,  313,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  314,  304,  316,  304,  304,  309,  317,  309,  309,

      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  304,  318,
      304,  309,  317,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  304,  319,  304,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  102,  304,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  304,  309,  309,  309,  309,  309,
      309,  309,  309,  304,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,

      309,  309,  309,    0,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304
    } ;

static const flex_int16_t yy_nxt[2608] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,    9,
       12,   13,   14,   15,    4,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   26,   26,
       29,   30,   31,   32,   33,   34,   35,   26,   36,   37,
       26,   26,   26,   26,   20,   21,   22,   23,   24,   25,
       27,   28,   26,   26,   29,   30,   31,   32,   33,   34,
       35,   26,   36,   37,   26,   26,    4,    4,    4,    4,
        4,   38,   39,   39,   39,   39,   39,   39,   45,   39,
       39,   39,  274,   44,   47,  265,  253,   43,   43,   48,
       43,   49,  106,   43,  156,   43,   44,   44,   43,   51,

      240,   43,   44,   43,   52,  238,   43,   53,   52,   43,
       44,   43,  107,   52,  108,   43,   71,  106,   44,  156,
      221,   43,  219,  193,   51,  196,  195,  193,   52,   66,
      154,   53,   52,   43,   67,  153,   43,   52,   43,   43,
       71,  151,   43,  110,   43,   44,   68,   54,   55,   43,
       69,   44,   43,   66,   43,   44,   42,   82,   67,   70,
      101,   44,   58,   57,   61,   56,   46,   44,   44,   42,
       62,   68,   63,   40,   64,   69,   43,  304,  304,   43,
      304,   43,   82,   70,  304,   65,  304,   43,   44,   61,
       43,  304,   43,  304,   62,  304,   63,  304,   64,   44,

      304,  304,   81,  304,   83,  304,  304,  304,   65,   43,
      304,  304,   43,   84,   43,  304,  304,  304,   85,   43,
      304,   44,   43,  304,   43,  304,   81,  304,  304,   83,
      304,   44,   72,   73,   74,  304,   94,   84,   75,  304,
      304,   76,   85,   43,  304,  304,   43,   43,   43,  304,
       43,  304,   43,  304,  304,   44,   72,   73,   74,   44,
      304,   94,   75,  100,  304,   76,   43,  304,  304,   43,
      304,   43,  304,   86,  304,  304,  304,   43,   44,   77,
       43,   43,   43,   78,   43,  304,   43,  100,  304,   44,
      304,  304,   79,   44,   80,   87,  304,   86,   90,  304,

      304,  304,   88,  304,   77,   89,  304,   91,   78,   43,
       43,  304,   43,   43,   43,   43,   79,  304,   80,  304,
       87,   44,   44,   90,  304,   43,   88,   92,   43,   89,
       43,   91,  304,  304,  304,  304,   93,   44,   43,  304,
      304,   43,   95,   43,  304,   96,  304,  304,  304,  304,
       44,  304,   92,   97,  304,   98,   43,   43,   43,  304,
       93,  304,  304,  304,   99,   44,  304,   95,  304,   96,
       43,   43,   43,  304,   43,   43,   43,   97,  304,   44,
       98,  304,  304,   44,   43,   43,   43,  304,   99,   59,
       43,  304,  304,   44,   43,   59,  304,   43,   59,   43,

       59,   59,  304,   59,   43,  304,   44,   59,   43,  304,
       43,  304,  304,   43,  304,   43,  105,  105,   43,   43,
       43,   43,   44,  304,  111,  304,  304,  304,   44,  304,
      105,  105,   59,  304,  105,  105,  304,   43,  112,  304,
       43,  304,   43,  304,  105,  105,  304,  109,  111,   44,
      113,  304,  304,   43,  304,   59,   59,   59,   59,   59,
       59,   47,  112,  304,   43,   43,   48,  114,   45,  304,
      304,  109,  304,   44,  304,  113,   51,  304,  304,  105,
      105,   52,  304,   43,   53,   52,   43,  304,   43,  304,
       52,  114,  304,  304,   43,   44,  304,   43,   43,   43,

      304,   51,  304,  304,  304,   52,   44,  304,   53,   52,
      115,  304,  304,  304,   52,   43,   43,  304,   43,   43,
       43,   43,  304,  304,   54,   55,  304,   44,   44,  117,
      304,   43,  304,  304,   43,  115,   43,   43,  304,  304,
       43,  304,   43,   44,  304,   43,  116,  118,   43,   44,
       43,  304,  119,  304,  117,  304,   43,   44,  304,   43,
      120,   43,   43,  304,  304,   43,  304,   43,   44,  304,
      116,  118,  304,  121,   44,   43,  119,  304,   43,  122,
       43,  304,  304,  304,  120,  304,  304,   44,  124,   43,
       43,  123,   43,   43,   43,   43,  304,  121,  304,  304,

      304,   44,   44,  122,   43,  125,  304,   43,  304,   43,
      304,  304,  304,  124,   43,  123,   44,   43,  304,   43,
      126,  127,  304,  304,   43,  304,   44,   43,   43,   43,
      125,   43,  304,   43,  304,  304,   44,  128,  304,  129,
       44,  304,   43,  130,  126,   43,  127,   43,   43,  304,
      304,   43,  304,   43,   44,  304,  304,  304,  304,  304,
       44,  128,   43,  131,  129,   43,   43,   43,  130,   43,
       43,   43,  304,   43,   44,   43,  132,  304,   44,  304,
       43,  304,   44,   43,  304,   43,  134,  131,  304,  304,
       43,  133,   44,   43,   43,   43,  304,   43,  304,   43,

      132,  304,   44,  304,   43,  304,   44,   43,  304,   43,
      135,  134,  137,  304,   43,  133,   44,   43,   43,   43,
      136,   43,  304,   43,   43,  304,   44,   43,  304,   43,
       44,  304,  304,  304,  135,   43,   44,  137,   43,  304,
       43,  304,  304,  304,  136,   43,  138,   44,   43,   43,
       43,  140,   43,  139,   43,  304,  304,   44,  141,   43,
      304,   44,   43,   43,   43,  304,   43,  142,   43,  304,
      138,   44,  304,  304,  143,   44,  140,  139,  304,  304,
      145,   43,  141,  144,   43,   43,   43,  304,   43,  304,
       43,  142,  304,   44,  304,  304,   43,   44,  143,   43,

      304,   43,  304,  304,  304,  145,   43,  144,   44,   43,
      147,   43,  146,   43,   43,   43,  304,  304,   44,  148,
      304,   43,   44,  149,   43,  304,   43,  150,   43,   43,
       43,  304,  304,   44,  147,  304,  146,   44,  304,  304,
      304,   43,  304,  148,   43,  304,   43,   43,  149,  304,
      304,  150,   59,   44,  160,  304,  304,  304,   59,  155,
      304,   59,   43,  152,   59,  304,   59,  304,  304,  304,
       59,  304,   43,  105,  105,   43,  304,   43,   43,  160,
      304,   43,   43,   43,   44,   43,  304,   43,  105,  105,
       44,  304,  304,  157,   44,   59,  304,  304,   43,  158,

      304,   43,   43,   43,  304,   43,  159,   43,  304,  304,
       44,  304,  304,  304,   44,  163,  304,  157,   59,   59,
       59,   59,   59,   59,  158,  161,   43,  304,  304,   43,
      159,   43,   43,  304,  304,   43,   43,   43,   44,   43,
      163,   43,   43,  304,   44,   43,  304,   43,   44,  161,
      304,  162,  304,  304,   44,  164,   43,  304,  304,   43,
       43,   43,  165,   43,   43,   43,  304,   43,   44,   43,
      166,  304,   44,  304,  304,  162,   44,  168,   43,  164,
      304,   43,  167,   43,   43,  169,  165,   43,   43,   43,
       44,   43,  304,   43,  166,  304,   44,  170,   43,  304,

       44,   43,  168,   43,  304,  304,  167,  304,   43,  169,
       44,   43,   43,   43,  304,   43,  171,   43,   43,  304,
       44,   43,  170,   43,   44,  304,  304,  172,  173,   43,
       44,  304,   43,  304,   43,  304,  304,  304,  174,  304,
      171,   44,  176,   43,  175,  304,   43,  304,   43,  304,
      304,  172,  173,   43,  304,   44,   43,  304,   43,  304,
      304,  304,  174,  304,  304,   44,   43,  176,  175,   43,
       43,   43,  177,   43,  304,   43,  304,  304,   44,  178,
      304,   43,   44,  179,   43,   43,   43,  304,   43,   43,
       43,  304,   43,   44,   43,   43,  177,   44,   43,   43,

       43,   44,   43,  178,   43,  304,  304,   44,  179,  304,
      181,   44,  304,  304,  180,   43,   43,  304,   43,   43,
       43,   43,  304,  304,  304,  182,  304,   44,   44,  304,
       43,  304,  304,   43,  181,   43,  304,  304,  180,  304,
      304,  183,   44,   43,  304,  184,   43,   43,   43,  182,
       43,  304,   43,  304,  304,   44,  304,  185,   43,   44,
      304,   43,  304,   43,  187,  183,  304,  304,  186,  184,
       44,   43,   43,  304,   43,   43,   43,   43,  304,  304,
      304,  185,  304,   44,   44,   43,   43,   43,  188,  187,
      304,  304,  186,   43,   44,  304,   43,  190,   43,  304,

      304,  304,  189,  304,   43,   44,  304,   43,   43,   43,
      304,   43,  188,   43,  304,  304,   44,  304,  304,   43,
       44,  190,  304,  191,   43,   43,  189,   43,   43,   43,
       43,  304,  304,  304,  304,  304,   44,   44,  304,   43,
      197,  198,   43,  304,   43,  105,  105,  191,   59,  199,
      304,   44,  304,  304,   59,  304,  200,   59,  102,   59,
       59,  102,   59,  304,  197,  304,   59,   43,  304,  304,
       43,   43,   43,  199,   43,  304,   43,  304,  304,   44,
      200,   43,  201,   44,   43,   43,   43,  304,   43,   43,
       43,   59,   43,   44,   43,  304,  304,   44,  304,  304,

       43,   44,  204,   43,  202,   43,  304,  201,  304,  304,
      304,  304,   44,  203,   59,   59,   59,   59,   59,   59,
       43,   43,  304,   43,   43,   43,   43,  204,  202,  304,
      304,   43,   44,   44,   43,   43,   43,  203,   43,  304,
       43,  304,  304,   44,  206,  304,  304,   44,  205,  304,
       43,  207,  304,   43,  304,   43,  304,  304,   43,  304,
      304,   43,   44,   43,  304,  304,  208,  209,  206,  304,
       44,  210,  205,  304,   43,   43,  207,   43,   43,   43,
       43,  304,  304,  304,  304,   43,   44,   44,   43,  208,
       43,  304,  209,  304,  304,   43,  210,   44,   43,  304,

       43,   43,  304,  304,   43,  304,   43,   44,  211,   43,
      304,  198,   43,   44,   43,   43,  304,  304,   43,   43,
       43,   44,   43,   43,   43,  304,   43,   44,   43,  304,
      304,   44,  304,  211,  213,   44,  212,   43,   43,  304,
       43,   43,   43,   43,  304,  214,  304,  304,  304,   44,
       44,  304,  304,   43,  304,  304,   43,  304,   43,  213,
      212,  304,  304,   43,  215,   44,   43,   43,   43,  214,
       43,   43,   43,  304,   43,   44,   43,   43,  304,   44,
       43,   43,   43,   44,   43,  304,   43,  304,  215,   44,
      216,   43,   43,   44,   43,   43,   43,   43,  304,  304,

      304,  217,  304,   44,   44,  222,   43,  304,  218,   43,
       43,   43,  304,   43,  304,   43,   43,  304,   44,   43,
      304,   43,   44,  304,  304,  217,  304,  304,   44,  224,
      222,  304,  304,  218,   59,  304,  225,  304,  304,  304,
       59,  304,  304,   59,  102,  152,   59,  102,   59,  304,
      304,  304,   59,  304,  224,  304,   43,  304,  304,   43,
      225,   43,   43,  304,  304,   43,   43,   43,   44,   43,
      304,   43,  304,  304,   44,  304,  304,   59,   44,  304,
       43,   43,  226,   43,   43,   43,   43,  304,  227,  304,
      304,  304,   44,   44,  304,  304,  228,  304,  304,  304,

       59,   59,   59,   59,   59,   59,  226,  304,   43,  304,
      304,   43,  227,   43,   43,  304,  304,   43,  304,   43,
       44,  228,   43,  304,  304,   43,   44,   43,  304,  304,
       43,  304,  304,   43,   44,   43,   43,  304,  304,   43,
      230,   43,   44,  304,   43,  229,  304,   43,   44,   43,
       43,  304,  304,   43,  304,   43,   44,  304,  304,  304,
      304,  304,   44,  232,  230,   43,  231,  304,   43,   43,
       43,  304,   43,   43,   43,  304,   43,   44,   43,   43,
      304,   44,   43,  304,   43,   44,  233,  304,  232,  304,
      231,   44,  235,  304,  304,   43,  304,  304,   43,   43,

       43,  234,   43,  304,   43,  236,  198,   44,  304,  304,
      233,   44,  237,  304,  304,   43,   43,  235,   43,   43,
       43,   43,  304,  304,  304,  234,  304,   44,   44,  236,
       43,   43,  241,   43,   43,   43,   43,  237,   59,  304,
      304,  304,   44,   44,   59,  304,  304,   59,  102,  152,
       59,  102,   59,  304,  304,  304,   59,  241,   43,   43,
      304,   43,   43,   43,   43,  304,  304,  198,  304,  304,
       44,   44,   43,   43,  304,   43,   43,   43,   43,  304,
      304,   59,  304,   43,   44,   44,   43,   43,   43,  304,
       43,  304,   43,  304,  242,   44,  304,  304,  244,   44,

      304,  304,  304,  243,   59,   59,   59,   59,   59,   59,
      304,   43,  246,  304,   43,  304,   43,  242,  304,  304,
      304,   43,  244,   44,   43,  304,   43,  243,  245,   43,
      304,  304,   43,   44,   43,  304,  246,   43,  304,  304,
       43,   44,   43,   43,  304,  304,   43,  247,   43,   44,
      304,   43,  249,  245,   43,   44,   43,  250,  304,  304,
      304,  304,  304,   44,  304,  304,  248,   43,  304,  304,
       43,  247,   43,  304,  304,  304,  251,  249,  304,   44,
      254,   43,  250,  304,   43,  304,   43,  304,  304,  304,
      304,  304,  304,   44,   43,  304,  304,   43,  304,   43,

      251,   59,  304,  304,  304,  254,   44,   59,  304,  304,
       59,  102,  152,   59,  102,   59,  304,  304,  198,   59,
      304,  304,  255,   43,   43,  304,   43,   43,   43,   43,
      304,  304,  304,  304,  304,   44,   44,  304,   43,  304,
      304,   43,   43,   43,   59,   43,  255,   43,  304,  256,
       44,  257,   43,   43,   44,   43,   43,   43,   43,  304,
      304,  304,  304,  304,   44,   44,  304,   59,   59,   59,
       59,   59,   59,  256,  304,  264,  257,  258,   43,   43,
      304,   43,   43,   43,   43,  304,  304,  304,  304,  304,
       44,   44,   43,  304,  304,   43,  304,   43,  304,  264,

      304,  258,   43,   43,   44,   43,   43,   43,   43,  263,
      304,  304,  304,  304,   44,   44,  266,  304,   43,  304,
      304,   43,  259,   43,  304,  260,  261,  304,  304,  198,
       44,   43,  262,  263,   43,   43,   43,  304,   43,   43,
       43,  266,   43,   44,   43,  304,  259,   44,  267,  260,
      261,   44,   43,  304,  304,   43,  262,   43,  304,  304,
      304,  304,   43,  304,   44,   43,  268,   43,   43,  304,
      269,   43,  267,   43,   44,  304,  304,  304,  270,  271,
       44,  304,  304,   43,   43,  304,   43,   43,   43,   43,
      268,  304,  304,  304,  269,   44,   44,  304,   43,  272,

      273,   43,  270,   43,  271,  304,   43,  304,  304,   43,
       44,   43,   43,  304,  304,   43,  304,   43,   44,  275,
      304,  198,  304,  272,   44,  273,   43,  304,  304,   43,
      276,   43,   43,  304,  304,   43,  304,   43,   44,  304,
      304,  304,  304,  275,   44,  304,  304,   43,  277,  304,
       43,  304,   43,  304,  276,  304,  279,  304,  278,   44,
      280,   43,  304,  304,   43,   43,   43,  304,   43,   43,
       43,  277,   43,   44,   43,  304,  304,   44,  304,  304,
      279,   44,  278,  282,   43,  280,  283,   43,  304,   43,
      304,  281,  304,  304,  304,  284,   44,   43,   43,  304,

       43,   43,   43,   43,  304,  304,  304,  304,  282,   44,
       44,  283,  304,  304,  304,  281,  304,   43,  285,  284,
       43,  304,   43,   43,  304,  286,   43,   43,   43,   44,
       43,   43,   43,  304,   43,   44,   43,  304,  304,   44,
      287,  304,  285,   44,  288,   43,  304,  289,   43,  286,
       43,   43,  304,  304,   43,   43,   43,   44,   43,  304,
       43,  304,  304,   44,  287,  304,   43,   44,  288,   43,
      304,   43,  289,  304,   43,  290,  304,   43,   44,   43,
      304,  304,   43,  304,  304,   43,   44,   43,   43,  304,
      304,   43,  291,   43,   44,  293,  304,  304,   43,  290,

       44,   43,   43,   43,  304,   43,  292,   43,  304,  294,
       44,  304,   43,   43,   44,   43,   43,   43,   43,  295,
      293,  304,  304,  304,   44,   44,  304,  304,  296,  297,
      292,  304,   43,  294,  304,   43,   43,   43,  304,   43,
      304,   43,  304,  295,   44,  304,  304,  304,   44,  298,
       43,  304,  296,   43,  297,   43,  304,  304,  304,  304,
      304,  299,   44,   43,   43,  304,   43,   43,   43,   43,
      304,  304,  304,  304,  298,   44,   44,   43,   43,  304,
       43,   43,   43,   43,  304,  299,  304,  304,  300,   44,
       44,  304,   43,   43,  301,   43,   43,   43,   43,  304,

      304,  304,  304,  304,   44,   44,  304,  302,  304,  304,
      304,  304,  300,  304,  304,  304,  304,  304,  301,  303,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  302,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  303,   41,   41,  304,  304,   41,   41,
       41,   41,   43,   43,   50,   50,  304,   50,   59,  304,
      304,  304,   59,   59,   59,   59,   60,   60,  102,  304,
      304,  304,  102,  102,  102,  102,  103,  103,  304,  103,
      103,  103,  103,  103,  104,  104,  304,  104,  105,  304,
      304,  105,  192,  192,  304,  304,  192,  192,  304,  192,

      194,  304,  304,  304,  194,  194,  194,  194,  220,  304,
      304,  304,  220,  220,  220,  220,  223,  223,  239,  304,
      304,  304,  239,  239,  239,  239,  252,  304,  304,  304,
      252,  252,  252,  252,    3,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,

      304,  304,  304,  304,  304,  304,  304
    } ;

static const flex_int16_t yy_chk[2608] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    5,    5,    5,    6,    6,    6,   12,   39,
       39,   39,  265,   12,   15,  253,  240,   15,   15,   15,
       23,   15,   48,   23,  110,   23,   15,   48,   26,   15,

      221,   26,   23,   26,   15,  219,   21,   15,   15,   21,
       26,   21,   49,   15,   49,  106,   23,  106,   21,  110,
      195,   15,  193,  192,   15,  154,  153,  151,   15,   21,
      108,   15,   15,   22,   21,  107,   22,   15,   22,   28,
       23,  101,   28,   55,   28,   22,   22,   15,   15,   20,
       22,   28,   20,   21,   20,   43,   41,   28,   21,   22,
       38,   20,   18,   17,   20,   16,   14,   13,    9,    8,
       20,   22,   20,    7,   20,   22,   27,    3,    0,   27,
        0,   27,   28,   22,    0,   20,    0,   29,   27,   20,
       29,    0,   29,    0,   20,    0,   20,    0,   20,   29,

        0,    0,   27,    0,   29,    0,    0,    0,   20,   24,
        0,    0,   24,   29,   24,    0,    0,    0,   29,   34,
        0,   24,   34,    0,   34,    0,   27,    0,    0,   29,
        0,   34,   24,   24,   24,    0,   34,   29,   24,    0,
        0,   24,   29,   37,    0,    0,   37,   30,   37,    0,
       30,    0,   30,    0,    0,   37,   24,   24,   24,   30,
        0,   34,   24,   37,    0,   24,   25,    0,    0,   25,
        0,   25,    0,   30,    0,    0,    0,   31,   25,   25,
       31,   32,   31,   25,   32,    0,   32,   37,    0,   31,
        0,    0,   25,   32,   25,   31,    0,   30,   32,    0,

        0,    0,   31,    0,   25,   31,    0,   32,   25,   60,
       33,    0,   60,   33,   60,   33,   25,    0,   25,    0,
       31,   60,   33,   32,    0,   35,   31,   33,   35,   31,
       35,   32,    0,    0,    0,    0,   33,   35,   36,    0,
        0,   36,   35,   36,    0,   35,    0,    0,    0,    0,
       36,    0,   33,   35,    0,   36,   47,   47,   47,    0,
       33,    0,    0,    0,   36,   47,    0,   35,    0,   35,
       50,   50,   50,    0,   51,   51,   51,   35,    0,   50,
       36,    0,    0,   51,   52,   52,   52,    0,   36,   44,
       47,    0,    0,   52,   61,   44,    0,   61,   44,   61,

       44,   44,    0,   44,   50,    0,   61,   44,   51,    0,
       62,    0,    0,   62,    0,   62,   47,   47,   52,   53,
       53,   53,   62,    0,   61,    0,    0,    0,   53,    0,
       50,   50,   44,    0,   51,   51,    0,   63,   62,    0,
       63,    0,   63,    0,   52,   52,    0,   53,   61,   63,
       63,    0,    0,   53,    0,   44,   44,   44,   44,   44,
       44,   45,   62,    0,   45,   45,   45,   63,   45,    0,
        0,   53,    0,   45,    0,   63,   45,    0,    0,   53,
       53,   45,    0,   71,   45,   45,   71,    0,   71,    0,
       45,   63,    0,    0,   64,   71,    0,   64,   45,   64,

        0,   45,    0,    0,    0,   45,   64,    0,   45,   45,
       64,    0,    0,    0,   45,   65,   66,    0,   65,   66,
       65,   66,    0,    0,   45,   45,    0,   65,   66,   66,
        0,   67,    0,    0,   67,   64,   67,   68,    0,    0,
       68,    0,   68,   67,    0,   69,   65,   66,   69,   68,
       69,    0,   67,    0,   66,    0,   70,   69,    0,   70,
       68,   70,   72,    0,    0,   72,    0,   72,   70,    0,
       65,   66,    0,   69,   72,   73,   67,    0,   73,   70,
       73,    0,    0,    0,   68,    0,    0,   73,   73,   74,
       75,   72,   74,   75,   74,   75,    0,   69,    0,    0,

        0,   74,   75,   70,   76,   74,    0,   76,    0,   76,
        0,    0,    0,   73,   77,   72,   76,   77,    0,   77,
       75,   76,    0,    0,   78,    0,   77,   78,   79,   78,
       74,   79,    0,   79,    0,    0,   78,   77,    0,   78,
       79,    0,   80,   79,   75,   80,   76,   80,   81,    0,
        0,   81,    0,   81,   80,    0,    0,    0,    0,    0,
       81,   77,   82,   80,   78,   82,   83,   82,   79,   83,
       84,   83,    0,   84,   82,   84,   81,    0,   83,    0,
       85,    0,   84,   85,    0,   85,   84,   80,    0,    0,
       86,   83,   85,   86,   87,   86,    0,   87,    0,   87,

       81,    0,   86,    0,   88,    0,   87,   88,    0,   88,
       85,   84,   87,    0,   89,   83,   88,   89,   90,   89,
       86,   90,    0,   90,   91,    0,   89,   91,    0,   91,
       90,    0,    0,    0,   85,   92,   91,   87,   92,    0,
       92,    0,    0,    0,   86,   93,   90,   92,   93,   94,
       93,   92,   94,   91,   94,    0,    0,   93,   92,   95,
        0,   94,   95,   96,   95,    0,   96,   93,   96,    0,
       90,   95,    0,    0,   94,   96,   92,   91,    0,    0,
       96,   97,   92,   95,   97,   98,   97,    0,   98,    0,
       98,   93,    0,   97,    0,    0,   99,   98,   94,   99,

        0,   99,    0,    0,    0,   96,  100,   95,   99,  100,
       98,  100,   97,  104,  104,  104,    0,    0,  100,   99,
        0,  115,  104,  100,  115,    0,  115,  100,  109,  109,
      109,    0,    0,  115,   98,    0,   97,  109,    0,    0,
        0,  114,    0,   99,  114,    0,  114,  104,  100,    0,
        0,  100,  102,  114,  114,    0,    0,    0,  102,  109,
        0,  102,  109,  102,  102,    0,  102,    0,    0,    0,
      102,    0,  111,  104,  104,  111,    0,  111,  113,  114,
        0,  113,  112,  113,  111,  112,    0,  112,  109,  109,
      113,    0,    0,  111,  112,  102,    0,    0,  118,  112,

        0,  118,  116,  118,    0,  116,  113,  116,    0,    0,
      118,    0,    0,    0,  116,  118,    0,  111,  102,  102,
      102,  102,  102,  102,  112,  116,  117,    0,    0,  117,
      113,  117,  119,    0,    0,  119,  120,  119,  117,  120,
      118,  120,  121,    0,  119,  121,    0,  121,  120,  116,
        0,  117,    0,    0,  121,  119,  122,    0,    0,  122,
      123,  122,  120,  123,  124,  123,    0,  124,  122,  124,
      121,    0,  123,    0,    0,  117,  124,  123,  125,  119,
        0,  125,  122,  125,  126,  124,  120,  126,  127,  126,
      125,  127,    0,  127,  121,    0,  126,  126,  128,    0,

      127,  128,  123,  128,    0,    0,  122,    0,  129,  124,
      128,  129,  130,  129,    0,  130,  127,  130,  131,    0,
      129,  131,  126,  131,  130,    0,    0,  128,  129,  132,
      131,    0,  132,    0,  132,    0,    0,    0,  130,    0,
      127,  132,  132,  133,  131,    0,  133,    0,  133,    0,
        0,  128,  129,  134,    0,  133,  134,    0,  134,    0,
        0,    0,  130,    0,    0,  134,  135,  132,  131,  135,
      136,  135,  133,  136,    0,  136,    0,    0,  135,  134,
        0,  137,  136,  135,  137,  138,  137,    0,  138,  139,
      138,    0,  139,  137,  139,  140,  133,  138,  140,  141,

      140,  139,  141,  134,  141,    0,    0,  140,  135,    0,
      139,  141,    0,    0,  138,  142,  143,    0,  142,  143,
      142,  143,    0,    0,    0,  141,    0,  142,  143,    0,
      144,    0,    0,  144,  139,  144,    0,    0,  138,    0,
        0,  142,  144,  145,    0,  143,  145,  146,  145,  141,
      146,    0,  146,    0,    0,  145,    0,  144,  147,  146,
        0,  147,    0,  147,  146,  142,    0,    0,  145,  143,
      147,  148,  149,    0,  148,  149,  148,  149,    0,    0,
        0,  144,    0,  148,  149,  155,  155,  155,  147,  146,
        0,    0,  145,  150,  155,    0,  150,  149,  150,    0,

        0,    0,  148,    0,  158,  150,    0,  158,  157,  158,
        0,  157,  147,  157,    0,    0,  158,    0,    0,  155,
      157,  149,    0,  150,  160,  159,  148,  160,  159,  160,
      159,    0,    0,    0,    0,    0,  160,  159,    0,  161,
      157,  158,  161,    0,  161,  155,  155,  150,  152,  159,
        0,  161,    0,    0,  152,    0,  160,  152,  152,  152,
      152,  152,  152,    0,  157,    0,  152,  162,    0,    0,
      162,  163,  162,  159,  163,    0,  163,    0,    0,  162,
      160,  164,  162,  163,  164,  165,  164,    0,  165,  166,
      165,  152,  166,  164,  166,    0,    0,  165,    0,    0,

      168,  166,  166,  168,  164,  168,    0,  162,    0,    0,
        0,    0,  168,  165,  152,  152,  152,  152,  152,  152,
      167,  169,    0,  167,  169,  167,  169,  166,  164,    0,
        0,  171,  167,  169,  171,  170,  171,  165,  170,    0,
      170,    0,    0,  171,  169,    0,    0,  170,  167,    0,
      172,  170,    0,  172,    0,  172,    0,    0,  173,    0,
        0,  173,  172,  173,    0,    0,  171,  172,  169,    0,
      173,  173,  167,    0,  174,  175,  170,  174,  175,  174,
      175,    0,    0,    0,    0,  176,  174,  175,  176,  171,
      176,    0,  172,    0,    0,  177,  173,  176,  177,    0,

      177,  178,    0,    0,  178,    0,  178,  177,  177,  179,
        0,  174,  179,  178,  179,  180,    0,    0,  180,  181,
      180,  179,  181,  182,  181,    0,  182,  180,  182,    0,
        0,  181,    0,  177,  181,  182,  180,  183,  184,    0,
      183,  184,  183,  184,    0,  182,    0,    0,    0,  183,
      184,    0,    0,  185,    0,    0,  185,    0,  185,  181,
      180,    0,    0,  186,  184,  185,  186,  187,  186,  182,
      187,  188,  187,    0,  188,  186,  188,  189,    0,  187,
      189,  190,  189,  188,  190,    0,  190,    0,  184,  189,
      185,  191,  197,  190,  191,  197,  191,  197,    0,    0,

        0,  189,    0,  191,  197,  197,  198,    0,  191,  198,
      200,  198,    0,  200,    0,  200,  199,    0,  198,  199,
        0,  199,  200,    0,    0,  189,    0,    0,  199,  199,
      197,    0,    0,  191,  194,    0,  200,    0,    0,    0,
      194,    0,    0,  194,  194,  194,  194,  194,  194,    0,
        0,    0,  194,    0,  199,    0,  201,    0,    0,  201,
      200,  201,  202,    0,    0,  202,  203,  202,  201,  203,
        0,  203,    0,    0,  202,    0,    0,  194,  203,    0,
      204,  205,  201,  204,  205,  204,  205,    0,  202,    0,
        0,    0,  204,  205,    0,    0,  204,    0,    0,    0,

      194,  194,  194,  194,  194,  194,  201,    0,  206,    0,
        0,  206,  202,  206,  207,    0,    0,  207,    0,  207,
      206,  204,  208,    0,    0,  208,  207,  208,    0,    0,
      209,    0,    0,  209,  208,  209,  210,    0,    0,  210,
      207,  210,  209,    0,  211,  206,    0,  211,  210,  211,
      212,    0,    0,  212,    0,  212,  211,    0,    0,    0,
        0,    0,  212,  212,  207,  213,  211,    0,  213,  214,
      213,    0,  214,  215,  214,    0,  215,  213,  215,  216,
        0,  214,  216,    0,  216,  215,  213,    0,  212,    0,
      211,  216,  216,    0,    0,  217,    0,    0,  217,  218,

      217,  215,  218,    0,  218,  216,  214,  217,    0,    0,
      213,  218,  217,    0,    0,  223,  222,  216,  223,  222,
      223,  222,    0,    0,    0,  215,    0,  223,  222,  216,
      224,  226,  222,  224,  226,  224,  226,  217,  220,    0,
        0,    0,  224,  226,  220,    0,    0,  220,  220,  220,
      220,  220,  220,    0,    0,    0,  220,  222,  225,  227,
        0,  225,  227,  225,  227,    0,    0,  224,    0,    0,
      225,  227,  228,  229,    0,  228,  229,  228,  229,    0,
        0,  220,    0,  230,  228,  229,  230,  232,  230,    0,
      232,    0,  232,    0,  225,  230,    0,    0,  229,  232,

        0,    0,    0,  228,  220,  220,  220,  220,  220,  220,
        0,  231,  232,    0,  231,    0,  231,  225,    0,    0,
        0,  233,  229,  231,  233,    0,  233,  228,  231,  234,
        0,    0,  234,  233,  234,    0,  232,  235,    0,    0,
      235,  234,  235,  236,    0,    0,  236,  233,  236,  235,
        0,  237,  235,  231,  237,  236,  237,  236,    0,    0,
        0,    0,    0,  237,    0,    0,  234,  241,    0,    0,
      241,  233,  241,    0,    0,    0,  237,  235,    0,  241,
      241,  242,  236,    0,  242,    0,  242,    0,    0,    0,
        0,    0,    0,  242,  243,    0,    0,  243,    0,  243,

      237,  239,    0,    0,    0,  241,  243,  239,    0,    0,
      239,  239,  239,  239,  239,  239,    0,    0,  242,  239,
        0,    0,  243,  244,  245,    0,  244,  245,  244,  245,
        0,    0,    0,    0,    0,  244,  245,    0,  246,    0,
        0,  246,  251,  246,  239,  251,  243,  251,    0,  244,
      246,  246,  247,  250,  251,  247,  250,  247,  250,    0,
        0,    0,    0,    0,  247,  250,    0,  239,  239,  239,
      239,  239,  239,  244,    0,  250,  246,  247,  254,  249,
        0,  254,  249,  254,  249,    0,    0,    0,    0,    0,
      254,  249,  257,    0,    0,  257,    0,  257,    0,  250,

        0,  247,  248,  255,  257,  248,  255,  248,  255,  249,
        0,    0,    0,    0,  248,  255,  255,    0,  256,    0,
        0,  256,  248,  256,    0,  248,  248,    0,    0,  257,
      256,  258,  248,  249,  258,  259,  258,    0,  259,  260,
      259,  255,  260,  258,  260,    0,  248,  259,  256,  248,
      248,  260,  261,    0,    0,  261,  248,  261,    0,    0,
        0,    0,  262,    0,  261,  262,  259,  262,  263,    0,
      260,  263,  256,  263,  262,    0,    0,    0,  261,  262,
      263,    0,    0,  264,  266,    0,  264,  266,  264,  266,
      259,    0,    0,    0,  260,  264,  266,    0,  267,  263,

      264,  267,  261,  267,  262,    0,  268,    0,    0,  268,
      267,  268,  269,    0,    0,  269,    0,  269,  268,  267,
        0,  266,    0,  263,  269,  264,  270,    0,    0,  270,
      268,  270,  271,    0,    0,  271,    0,  271,  270,    0,
        0,    0,    0,  267,  271,    0,    0,  272,  269,    0,
      272,    0,  272,    0,  268,    0,  271,    0,  270,  272,
      272,  273,    0,    0,  273,  275,  273,    0,  275,  276,
      275,  269,  276,  273,  276,    0,    0,  275,    0,    0,
      271,  276,  270,  275,  277,  272,  276,  277,    0,  277,
        0,  273,    0,    0,    0,  276,  277,  278,  279,    0,

      278,  279,  278,  279,    0,    0,    0,    0,  275,  278,
      279,  276,    0,    0,    0,  273,    0,  280,  278,  276,
      280,    0,  280,  281,    0,  279,  281,  282,  281,  280,
      282,  283,  282,    0,  283,  281,  283,    0,    0,  282,
      280,    0,  278,  283,  281,  284,    0,  283,  284,  279,
      284,  285,    0,    0,  285,  286,  285,  284,  286,    0,
      286,    0,    0,  285,  280,    0,  287,  286,  281,  287,
        0,  287,  283,    0,  288,  285,    0,  288,  287,  288,
        0,    0,  289,    0,    0,  289,  288,  289,  290,    0,
        0,  290,  286,  290,  289,  289,    0,    0,  291,  285,

      290,  291,  292,  291,    0,  292,  288,  292,    0,  290,
      291,    0,  296,  293,  292,  296,  293,  296,  293,  291,
      289,    0,    0,    0,  296,  293,    0,    0,  292,  293,
      288,    0,  294,  290,    0,  294,  295,  294,    0,  295,
        0,  295,    0,  291,  294,    0,    0,    0,  295,  294,
      297,    0,  292,  297,  293,  297,    0,    0,    0,    0,
        0,  295,  297,  298,  299,    0,  298,  299,  298,  299,
        0,    0,    0,    0,  294,  298,  299,  300,  301,    0,
      300,  301,  300,  301,    0,  295,    0,    0,  298,  300,
      301,    0,  303,  302,  299,  303,  302,  303,  302,    0,

        0,    0,    0,    0,  303,  302,    0,  300,    0,    0,
        0,    0,  298,    0,    0,    0,    0,    0,  299,  302,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  300,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  302,  305,  305,    0,    0,  305,  305,
      305,  305,  306,  306,  307,  307,    0,  307,  308,    0,
        0,    0,  308,  308,  308,  308,  309,  309,  310,    0,
        0,    0,  310,  310,  310,  310,  311,  311,    0,  311,
      311,  311,  311,  311,  312,  312,    0,  312,  313,    0,
        0,  313,  314,  314,    0,    0,  314,  314,    0,  314,

      315,    0,    0,    0,  315,  315,  315,  315,  316,    0,
        0,    0,  316,  316,  316,  316,  317,  317,  318,    0,
        0,    0,  318,  318,  318,  318,  319,    0,    0,    0,
      319,  319,  319,  319,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,

      304,  304,  304,  304,  304,  304,  304
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[47] =
    {   0,
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "smart_home_parser.l"
/* Lexer SMART-HOME para conectar con Bison.
   Devuelve tokens al parser y reporta errores lexicos con linea y lexema. */
#define YY_NO_INPUT 1
#line 11 "smart_home_parser.l"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "parser.tab.h"

int errores_lexicos = 0;
int linea_token = 1;

static char *copiar_yytext(void) {
    size_t n = strlen(yytext);
    char *r = (char *)malloc(n + 1);
    if (!r) exit(1);
    memcpy(r, yytext, n + 1);
    return r;
}

#define RET(tok) do { linea_token = yylineno; yylval.texto = copiar_yytext(); return tok; } while (0)
#define LEXERR(msg) do { linea_token = yylineno; errores_lexicos++; fprintf(stderr, "[ERROR LEXICO] Linea %d: %s cerca de '%s'\n", yylineno, msg, yytext); yylval.texto = copiar_yytext(); return TOK_ERROR_LEXICO; } while (0)
#line 1172 "lex.parser.c"
#line 1173 "lex.parser.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 47 "smart_home_parser.l"


#line 1391 "lex.parser.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 305 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 2535 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 49 "smart_home_parser.l"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 50 "smart_home_parser.l"
;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 52 "smart_home_parser.l"
{ RET(TOK_WHEN); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 53 "smart_home_parser.l"
{ RET(TOK_EVERY); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 54 "smart_home_parser.l"
{ RET(TOK_IF); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 55 "smart_home_parser.l"
{ RET(TOK_THEN); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 56 "smart_home_parser.l"
{ RET(TOK_ELSE); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 57 "smart_home_parser.l"
{ RET(TOK_DO); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 58 "smart_home_parser.l"
{ RET(TOK_END); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 59 "smart_home_parser.l"
{ RET(TOK_AND); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 60 "smart_home_parser.l"
{ RET(TOK_OR); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 61 "smart_home_parser.l"
{ RET(TOK_NOT); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 63 "smart_home_parser.l"
{ RET(TOK_BOOL); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 65 "smart_home_parser.l"
{ RET(TOK_MODO); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 66 "smart_home_parser.l"
{ RET(TOK_COLOR); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 68 "smart_home_parser.l"
{ RET(TOK_ID_SENSOR_NUM); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 69 "smart_home_parser.l"
{ RET(TOK_ID_SENSOR_BOOL); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 71 "smart_home_parser.l"
{ RET(TOK_ID_DISPOSITIVO); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 72 "smart_home_parser.l"
{ RET(TOK_ID_DISPOSITIVO); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 74 "smart_home_parser.l"
{ RET(TOK_ATRIBUTO); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 76 "smart_home_parser.l"
{ RET(TOK_EMAIL); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 77 "smart_home_parser.l"
{ LEXERR("email invalido"); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 78 "smart_home_parser.l"
{ RET(TOK_TEXTO); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 79 "smart_home_parser.l"
{ RET(TOK_TEXTO); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 80 "smart_home_parser.l"
{ RET(TOK_HORA); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 81 "smart_home_parser.l"
{ RET(TOK_FECHA); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 82 "smart_home_parser.l"
{ RET(TOK_NUM_TEMP); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 83 "smart_home_parser.l"
{ RET(TOK_PERCENT); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 84 "smart_home_parser.l"
{ RET(TOK_TIME); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 85 "smart_home_parser.l"
{ RET(TOK_LUX); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 86 "smart_home_parser.l"
{ LEXERR("unidad numerica invalida"); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 87 "smart_home_parser.l"
{ RET(TOK_NUMERO); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 89 "smart_home_parser.l"
{ RET(TOK_IGUALDAD); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 90 "smart_home_parser.l"
{ RET(TOK_DIFERENTE); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 91 "smart_home_parser.l"
{ RET(TOK_MAYOR_IGUAL); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 92 "smart_home_parser.l"
{ RET(TOK_MENOR_IGUAL); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 93 "smart_home_parser.l"
{ RET(TOK_IGUAL); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 94 "smart_home_parser.l"
{ RET(TOK_MAYOR); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 95 "smart_home_parser.l"
{ RET(TOK_MENOR); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 96 "smart_home_parser.l"
{ RET(TOK_PUNTO); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 97 "smart_home_parser.l"
{ RET(TOK_PARENTESIS_ABRE); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 98 "smart_home_parser.l"
{ RET(TOK_PARENTESIS_CIERRA); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 100 "smart_home_parser.l"
{ RET(TOK_ID); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 101 "smart_home_parser.l"
{ LEXERR("arroba fuera de un email valido"); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 102 "smart_home_parser.l"
{ LEXERR("simbolo o cadena no reconocida"); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 104 "smart_home_parser.l"
ECHO;
	YY_BREAK
#line 1689 "lex.parser.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 305 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 305 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 304);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 104 "smart_home_parser.l"


